### DISCUSSION TITLE
AZDO pass secret to bicep parameters file

### DISCUSSION THREAD

**Discussion by tonyeung** [Azure/azure-dev#2290] [Q&A] [answered]
I'm getting the below error. 
I've set the secret variable and mapped it via the yaml.
Still getting the same error.

```
ERROR: deployment failed: failing invoking action 'provision', planning deployment: planning infrastructure provisioning: prompting for value: no default response for prompt 'Please enter a value for the 'secret' infrastructure parameter:'
##[error]Script failed with exit code: 1
```

main.parameters.json
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "secret": {
      "value": "${secret}"
    },
...
```
azure-dev.yaml
```
steps:
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.
  - task: AzureCLI@2
    displayName: Azure Dev Provision
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      secret: $(secret)
```
