### DISCUSSION TITLE
Would be nice if I could specify the deployment target of a service to an output from my Bicep deployment

### DISCUSSION THREAD

**Discussion by mbenko** [Azure/azure-dev#26] [General]
``The azure.yaml file includes a project: attribute that defines where the code for the service lives and the language attribute tells me how to build it. It would be nice if I could specify the destination name of the azure service I'd like to deploy to. The data could be stored in the environment configuration (resource group name, etc). Also would be nice to specify the name of the resource group to deploy to. something like
```
services:
  web:
    project: myApp
    language: csharp
    host: appservice
    hostname: outputs.siteName
```
