### DISCUSSION TITLE
How to deploy to a deployment slot of App Service using azd deploy?

### DISCUSSION THREAD

**Discussion by 290ch** [Azure/azure-dev#2641] [Q&A] [answered]
I am having trouble figuring out how to deploy to a specific slot using azd deploy. 

What I have is this - 
```yaml
...
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
  backenddev:
    project: ./app/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
```

where **backend** is the production, and **backenddev** is meant to be for dev slot.
I tagged my dev slot with **azd-service-name: backenddev**.
When I run **azd deploy backenddev**, I get the following error:

```ERROR: failed deploying service 'backenddev': failing invoking action 'deploy', validating target resource: resource 'app-backend-xxxxxxxx/dev' with type 'Microsoft.Web/sites/slots' does not match expected resource type 'Microsoft.Web/sites'```

Is deploying to a slot using azd not supported? How should I go about doing this?
