### DISCUSSION TITLE
Support multi-contexts docker build with buildx bake

### DISCUSSION THREAD

**Discussion by AlexisMtr** [Azure/azure-dev#3539] [Ideas]
I work on context where we need multi-context build and overwritten contexts to build our container images.

Some companies have security tools that prevent us from building images or downloading dependencies without a custom certificate, but on CI process, this certificate is not needed so we can't put it on the Dockerfile.

Buildx Bake offer a solution to orchestrate the builds and it can be good to have it on `azd` CLI

I started to implement it (https://github.com/AlexisMtr/azure-dev/tree/docker-bake-support), but I'm not a Go developer and I haven't a deep understanding on how this project is architecture, I'm not the best to implement I guess

Maybe, it can be useful for https://github.com/Azure/azure-dev/pull/3457 as builx bake allow to build more than one container in a single run.

An exemple is sometimes better 😉

```bash
.
├── azure.yaml
├── docker-bake.hcl
└── src
    ├── Project.Domain
    │   └── Project.Domain.csproj
    ├── ... # many projects not needed to build Project.Api
    ├── Project.Api
    │   ├── Project.Api.csproj
    │   ├── Dockerfile
    └── Project.sln
```

With Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /src
COPY --from=domain Project.Domain.csproj Project.Domain/
COPY Project.Api.csproj Project.Api/
RUN dotnet restore Project.Api/Project.Api.csproj
COPY --from=domain . Project.Domain/
COPY . Project.Api/
RUN dotnet publish Project.Api/Project.Api.csproj --no-restore -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:7.0 as final
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Project.Api.dll"]
```

And docker-bake.hcl
```hcl
target "custom-certificate" {
  dockerfile-inline = <<EOT
FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
COPY --from=certificates ./custom.pem /etc/ssl/certs/custom.pem
EOT
  contexts = {
    certificates = "/path/to/custom/certs/"
  }
}

target "api-proj" {
  context = "./src/Project.Api/"
  contexts = {
    domain = "./src/Project.Domain/"
  }
}

target "api-proj-custom-certificate" {
  inherits = [ "api-proj" ]
  contexts = {
    "mcr.microsoft.com/dotnet/sdk:7.0" = "target:custom-certifciate"
  }
}
```

We can imaging having an azure.yaml that look like

```yaml
name: project
metadata:
services:
  api:
    project: ./src/Project.Api
    language: dotnet
    host: containerapp
    docker:
      bake:
        definition: docker-bake.hcl
        # change by "api-proj-custom-certificate" if your build depends on custom certificates
        target: api-proj
        # this property allow to run using docker-bake.hcl in root folder and not on service folder
        # to not have to change the definition of Bake just for azd CLI
        useServiceContext: false
```

With this kind of solution, in this exemple, someone without the certificate constraint can build the image using `docker buildx bake api-proj` while someone with the constraint can run `docker buildx bake api-proj-custom-certificate` without any changes on the Dockerfile
