### DISCUSSION TITLE
Help with azd deploy in sample Devops pipeline - fails with "not logged in" error

### DISCUSSION THREAD

**Discussion by kevcrooks** [Azure/azure-dev#4134] [General]
I'm attempting to use the sample pipeline here:
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=azdo

I've set up the pipeline correctly, and run on Azure Devops. The problem is that the `azd provision` step works fine, but when it gets to the `azd deploy` step, I get the following error:
```
ERROR: getting resource group name: getting resource group for environment: XXXX: not logged in, run `azd auth login` to login
```

I'm not sure why this is happening, since the `provision` step worked, and in the logs I'm seeing that it is connecting:
```
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription XXXX"
```

Does anyone have advice on how to get this working? My understanding is that the `azd config set auth...` step should have sorted all the login for me?

**Comment by vhvb1989** [comment]
Can you share your pipeline yaml definition?

Are you using a federated-credential for your service connection?  (did you use azd pipeline config? )
Try using `keepAzSessionActive: true` AzureCLIV2` task, like

```
- task: AzureCLI@2
      displayName: Deploy Application
      inputs:
         azureSubscription: azconnection
         keepAzSessionActive: true
         scriptType: bash
         scriptLocation: inlineScript
         inlineScript: |
         azd deploy --no-prompt
```
