### DISCUSSION TITLE
Deploying aspire blazor app, how to use build package from a previous stage in Azure Devops

### DISCUSSION THREAD

**Discussion by mip1983** [Azure/azure-dev#4141] [Q&A]
I've an Azure DevOps pipeline which was based on the yaml template from aspire, but I've evolved to do a bit more, broken into stages, running tests, approvals and deployments to different environments.

The steps where I run 'azd deploy' take quite a while (because it's a Blazor app with AOT, so takes some crunching to produce publish output), and because it's going to different environments at different build stages, this long build runs multiple times.

As such, I've been trying to create a build/publish step up front with the output of that available to subsequent steps, hoping to prevent azd needing to create the publish output each time. However, the docs seems a bit sparse on this from what I've found, so am struggling.

Here's an example of the deploy step I'm trying at the moment:

```
- task: AzureCLI@2
      displayName: 'Deploy API application to staging'
      condition: and(succeeded(), ${{ eq(parameters.releaseStaging, true) }})
      inputs:
        azureSubscription: 'azureDevServiceConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'azd deploy web'
        arguments: '--from-package $(Pipeline.Workspace)\drop\web.zip --no-prompt --debug'
        workingDirectory: '<codecheckoutfolderhere>'
      env:
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        AZURE_ENV_NAME: $(AZURE_ENV_NAME)
        AZURE_LOCATION: $(AZURE_LOCATION)
        AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)
```

However, it doesn't seem like '--from-package' does anything and it just starts 'Analyzing Aspire Application'  and builds/publishes from source.

How do I go about doing this?
