### DISCUSSION TITLE
March v1.13.0 release discussion

### DISCUSSION THREAD

**Discussion by kristenwomack** [Azure/azure-dev#4902] [General]
March [release v1.13.0](https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_1.13.0) is out now! 📦🎉

[Blog post](https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-march-2025/)

We hope you enjoy the new features. Happy deploying. 👩‍💻

💻 [Windows](https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/latest/azd-windows-amd64.zip) | [Linux](https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/latest/azd-linux-amd64.tar.gz) | [Mac](https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/latest/azd-darwin-amd64.zip)
💻 vscode extension [VSIX](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azure-dev)

**Comment by torumakabe** [comment]
Congratulations on the release. Do you have any documentation on how to use the language type `docker`?

**Comment by rajeshkamal5050** [comment]
Thanks for reaching out @torumakabe 

For example to get golang apps deployed in ACA,
- Sample project - https://github.com/GoogleCloudPlatform/golang-samples/tree/main/run/helloworld
- Needed basic azure.yaml with `language` type as `docker` 
```
name: helloworld
services:
    helloworld:
        project: .
        host: containerapp
        language: docker
resources:
    helloworld:
        type: host.containerapp
        port: 8080
```
- Run azd up workflow.

cc @alexwolfmsft for including in our docs.
