### DISCUSSION TITLE
Passing in custom Env vars to be replaced in container.tmpl.yaml

### DISCUSSION THREAD

**Discussion by rozatoo** [Azure/azure-dev#4950] [Q&A]
I'm noticing that when I run `azd up`, placeholders in the containers YAML inside the Apphost like these:

```yaml
api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
```

are automatically replaced with their corresponding values. I'm wondering if it's possible to define custom environment variables that work the same way.

For example, if I execute:

```bash
azd env set TEST_ENV_VALUE test
```

can I have that value injected into my container YAML? Ideally, I’d like to have something like:

```yaml
template:
  containers:
    - image: {{ .Image }}
      name: containername
      env:
        - name: TEST_VALUE
          value: {{ .Env.TEST_ENV_VALUE }}
```

automatically transformed to:

```yaml
template:
  containers:
    - image: image:1234
      name: containername
      env:
        - name: TEST_VALUE
          value: test
```

I tried this but got the error:

```
ERROR: error executing step command 'deploy --all': failed deploying service 'containername': failed executing template file: template: manifest template:34:34: executing "manifest template" at <.Env.TEST_ENV_VALUE>: map has no entry for key "TEST_ENV_VALUE"
```

I know I could use `envsubst` or another replacement tool, but it would be great to use `azd` since it already handles predefined variables. Is this functionality possible in any way?
