### DISCUSSION TITLE
Access object output from main.bicep

### DISCUSSION THREAD

**Discussion by CWWallin** [Azure/azure-dev#5096] [Q&A]
In container tmpl.yaml files how can I access an object output from main.bicep? My first thought was something like this:
`{{ .Env.MyObjectOutput.MyValue }}`

That didn't seem to do the trick. Anyone have any ideas or know how to use objects in Container App yaml files? 

I'm deploying with Azure Pipelines to multiple environments and have specified settings for each environment in my bicep files, but I need to use object as an output otherwise I will reach bicep output limitations of 64 outputs.

**Comment by vhvb1989** [comment]
`.Env` currently represents the azd-environment.

For what you are trying to do, you need to add one step in your pipeline to set the variables/secrets from your pipeline into azd's environment.  For example:

```yaml
      - name: Init azd env and set required variables
        run: |
          azd env set MyObjectOutput MyValue 
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
          MyValue: ${{ variables.MyValue }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt

      - name: Deploy Application
        run: azd deploy --no-prompt

```

This should make AZD to find `MyObjectOutput` as a key in azd's environment.
