### DISCUSSION TITLE
`azure.yaml` schema change to support Java build tool (maven, gradle)

### DISCUSSION THREAD

**Discussion by weikanglim** [Azure/azure-dev#740] [Ideas]
# Java build tool support
Our current plan is to support [Maven](https://maven.apache.org/) build tool for the initial Java release. This also includes the support of the popular [Maven wrapper](https://maven.apache.org/wrapper/) / `mvnw` plugin that is packaged as part of Java repositories. The main usage of `mvnw` is to simplify maven installation for Java users, and also to lock down the specific maven version used to build a given Java repository.

With this change, we'll need to introduce a new field, `buildTool` in `azure.yaml` to define what build tool the user wants to target.

### Option A: Explicit

The schema explicitly requires the user to specify a `buildTool` value. If unset, a validation error is generated.

#### Case: buildTool unspecified

```yaml
api:
    project: ./src/api
    language: java
```

#### Result:
An error is generated: `Missing property "buildTool"`

![image](https://user-images.githubusercontent.com/2322434/192031443-f7a0dd72-2fc3-4a19-9420-b43e20ee37b7.png)

#### Case: buildTool specified

```yaml
api:
    project: ./src/api
    language: java
    buildTool: maven
```

#### Result:
The schema is valid and `azd` uses `maven` as the build tool.

### Option B: Implicit

The schema implicitly assumes `buildTool` is set to `maven` by default, allowing for an override value if specified.

#### Case: buildTool unspecified

```yaml
api:
    project: ./src/api
    language: java
```

#### Result:
`azd` will use `maven` as part of packaging implicitly.

#### Case: buildTool specified

```yaml
api:
    project: ./src/api
    language: java
    buildTool: gradle
```

#### Result:
`azd` will use `gradle` as part of packaging.

### Option C: Implicit by presence of configuration files

We will infer the build-tool of choice by looking for project configuration files:
- Maven - `pom.xml`
- Gradle - `settings.gradle` or `settings.gradle.kotl`

Maven will be chosen by default if both are present -- Having two project builds isn't something I think we would support.
