### ISSUE TITLE
The azd version in the github pipeline does not support the azd login --client-id parameter.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1134]
**Describe the issue:**
The `azd` version in the github pipeline does not support the azd login `--client-id` parameter when execute `azd pipeline config`.

**Repro Steps:**

1. Execute command: `bash ./test-templates.sh -c false -t Azure-Samples/todo-nodejs-mongo -b pr/1129 -s ***`.
2. Run: `azd pipeline config`.
3. Click on the link that is printed to open the actions page and you will see:
![image](https://user-images.githubusercontent.com/81678720/201311791-4b06aa73-7294-4b98-a042-021bc4e747e1.png)

**Environment:**
OS: WSL, MacOS desktop, Windows desktop, Linux desktop
Template: https://github.com/azure-samples/todo-nodejs-mongo
Azd version: 0.4.0-beta.1-pr.1982037 (commit https://github.com/Azure/azure-dev/commit/0cb9c7c50e1fcdd8b0821587548e8c2a57023666)
Branch: [pr/1129](https://github.com/Azure/azure-dev/pull/1129)
**With Az CLI** and **Without Az CLI**

**Expected behavior:**
Action logs can pass successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@ellismg @vhvb1989 can you triage if this is a generic pipeline issue or anything w.r.t to the azd authn changes?

Note: this failure was on the PR branch https://github.com/Azure/azure-dev/pull/1129

**Comment by ellismg** [comment]
I suspect the problem here is that the pipeline references the currently shipped version of the container that has `azd` in it:

https://github.com/Azure-Samples/todo-nodejs-mongo/blob/1b9bca5f3d9ef91ef5550d3fa0397d4eba119a09/.github/workflows/azure-dev.yml#L20-L21

But this has not been updated to include the version of `azd` that uses our own authentication.

```
C:\dd\azure\azure-dev>docker run --rm -it mcr.microsoft.com/azure-dev-cli-apps:latest azd version
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
```

We have a published version of the container in the PR with this name: `azdevcliextacr.azurecr.io/azure-dev:pr-1129`

For testing purposes, we should either modify the azure-dev.yml pipeline in the test repository to reference this image, or alternately add an additional step to the pipeline that does this:

```yaml
      - name: Install Private AZD
        run: |
          curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1129/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/1129 --version '' --verbose

```

To install the private bits.
