### ISSUE TITLE
ADO template does not use AZ Login flow

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#1395]
**Output from `azd version`**
```
azd version 0.5.0-beta.2 (commit 4f95806a0a8f5cb4187267ca75dcff8be71fd95d)
```

**Output from `az version`** 
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.13",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.4"
  }
}
```

**Describe the bug**
Errors from ADO pipeline file that I received after running `azd init` and choosing the `todo-csharp-sql@0.0.1-beta` template

**To Reproduce**
1. Run `azd init`
2. Observe the `azure-dev.yml` file for ADO pipeline, it does not call `azd login` and fails when trying to run `azd provision`

**Expected behavior**
The ADO pipeline can run `azd provision`

**Comment by ellismg** [comment]
#1126 is another instance of this same issue.  At the time when we added `azd login` it wasn't 100% obvious how to have it work correctly in Azdo:

IIRC, the crux of the issue was it wasn't obvious how to get the relevant pieces of metadata we needed to call `azd login` from the connection to the azure subscription.

The existing pipelines have this:

```
  - task: AzureCLI@2
    displayName: Azure Dev Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
 ``` 
 
I suspect that we need to be able to extract the client-id, tenant-id and client-secret from this `azconnection` thing that is passed to `azureSubscription` and then use that to call `azd login`.

@KSchlobohm - If you have an idea as to what we need to be doing here in our templates to get `azd login` to work, happy to make changes.  In the short term we updated these pipelines to delegate to the `az` CLI for authentication since that was already working.

**Comment by wbreza** [comment]
@ellismg - Looks like there are ways to get properties of the ServiceConnection.  It is pretty verbose and we should likely either create our own Azdo task or update our samples.

**AzureCLI@2**
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV2/azureclitask.ts#L106

**Comment by wbreza** [comment]
In the meantime a workaround for this issue would be use use the following step that will setup azd to use Az CLI for login.

**Step to set AZD to use Az CLI for auth**
```yaml
- pwsh: |
    azd config set auth.useAzCliAuth "true"
```

**Full working Azdo Pipeline**
```yaml
trigger:
  - main
  - master

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/azure-dev-cli-apps:latest

steps:
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.
  - task: AzureCLI@2
    displayName: Azure Dev Provision
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      
  - task: AzureCLI@2
    displayName: Azure Dev Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
```
