### ISSUE TITLE
[Issue] JSON validation for OS specific hooks

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1552]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit https://github.com/Azure/azure-dev/commit/c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Output from `az version`** 

n/a - not relevant for my scenario

**Describe the bug**

When adding OS dependent configurations to the `azure.yaml` file, VSCode depicts an error due to a missing `run`

![os-specific-hook-validation](https://user-images.githubusercontent.com/22294087/218325150-c9ce7f79-a3a1-4fbd-9616-bb71ef50b785.png)

This is due to the structure of the JSON schema that requires a `run` on top-level of the hook. According to the documentation the syntax like:

```yaml
name: todo-nodejs-mongo
metadata:
  template: todo-nodejs-mongo@0.0.1-beta
hooks:
  preinit: 
    posix: # Only runs on Posix environments
      shell: sh
      run: echo 'Hello'
   windows: # Only runs on Windows environments
     shell: pwsh
     run: Write-Host "Hello
```

is valid.

**To Reproduce**

Add a OS dependent configuration to your `azure.yaml` file.

**Expected behavior**

The validation should not show any error when adding OS specific configurations even if a `run` on top-level is missing

**Environment**

VSCode 1.75.1

**Additional context**

n/a
