### ISSUE TITLE
service hook: unable to determine script type

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1579]
Error message should be moer user-friendly. I'm still unsure what happened.

todo-nodejs with the following applied, running on Windows.
```yaml
  web:
    project: ./src/web
    dist: build
    language: js
    host: appservice
    hooks:
      predeploy:
        shell: sh
        run: npm run test
        interactive: true       
```

```
PS C:\demos\todo> azd deploy   

Deploying services (azd deploy)

  (✓) Done: Deploying service api
  - Endpoint: https://app-api-xxxx.azurewebsites.net/
  (✓) Done: Deploying service web

ERROR: deploying service: failed invoking event handlers for 'predeploy', failed running scripts for hooks 'deploy', hook configuration for 'predeploy' is invalid, unable to determine script type. Ensure 'Shell' parameter is set in configuration options
```
