### ISSUE TITLE
[Issue] Add template-analyser and bicep linter to templates

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-dev#1640]
I'd like to suggest the following workflow to be added to template repositories.

It will run 2 analyzers over the bicep files, designed to be run on PRs and on commits to main/master

1. The builtin bicep linter
2. The Azure Defender for DevOps' templateanalyzer tool which compares the bicep against the best-practices

```yaml
name: Validate bicep scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Bicep for linting
        uses: azure/CLI@v1
        with:
          inlineScript: az bicep build -f infra/main.bicep --stdout

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
```

Results go into the security report in GitHub like this:

<img width="1883" alt="screenshot 2023-03-02 at 12 46 52" src="https://user-images.githubusercontent.com/1532417/222314181-7a69ded9-37cb-41ab-8c3b-9185ba95fec1.png">
