### ISSUE TITLE
Change project build/deploy order by order in azure.yaml not alpha

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1678]
Right now it's alpha.  Let's change to order of yaml.

**Comment by weikanglim** [comment]
It does seem that this is possible. `golang`'s yaml parser supports it with [MapSlice](https://pkg.go.dev/gopkg.in/yaml.v2#MapSlice).

However, I'm still really hesitant on this. This requires us to introduce a new constraint on top of `yaml`. `yaml` [specification ](https://yaml.org/spec/1.2.2/#3221-mapping-key-order) clearly states:

> In the representation model, mapping keys do not have an order. To serialize a mapping, it is necessary to impose an ordering on its keys. This order is a serialization detail and should not be used when composing the representation graph (and hence for the preservation of application data). In every case where node order is significant, a sequence must be used. For example, an ordered mapping can be represented as a sequence of mappings, where each mapping is a single key/value pair. YAML provides convenient compact notation for this case.

This means that any tool that parses `azure.yaml` would need to conform to `azd-yaml` specification for processing `services` instead of `yaml`.

**Comment by weikanglim** [comment]
I would propose that we would move our yaml schema from:

```yaml
services:
  api:
    language: dotnet
    host: appservice
    project: ./src/api
```

to:

```yaml
services:
  name: api:
  language: dotnet
  host: appservice
  project: ./src/api
```

This correctly conveys the ordering semantics in `yaml`.  If the new schema is adopted, the services are deployed in the order specified. Fixed alphabetical ordering for the old schema.
