### ISSUE TITLE
[Issue] azure.yaml schema issue - missing property run

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1800]
![image](https://user-images.githubusercontent.com/2163001/228052747-5957658a-3ac0-4541-a527-7a7e42de8a93.png)

example yaml
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
hooks:
    postprovision:
      windows:
        shell: pwsh
        run: ./scripts/prepdocs.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/prepdocs.sh
        interactive: true
        continueOnError: false
    predeploy:
      windows:
        shell: pwsh
        run:  cd ./app/frontend;npm install;npm run build
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run:  cd ./app/frontend;npm install;npm run build
        interactive: true
        continueOnError: false
```
