### ISSUE TITLE
[Issue] Misplaced hooks results in confusing error message

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1802]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**

I accidentally had a yaml like this:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ms-identity-python-webapp

services:
  hooks:
    postprovision:
      shell: bash
      run: ./update_env.sh
  web:
    project: .
    language: py
    host: appservice
```

When I ran `azd provision`, I got this message:

ERROR: failed to initialize secrets at project '/Users/pamelafox/ms-identity-python-webapp': exec: "dotnet": executable file not found in $PATH (exit code: 0, stdout: , stderr: )

I was super confused as to why it was trying to execute dotnet, so I traced that code in the azure-dev code and then realized it was misinterpreting my hooks as a project, and I'm guessing projects default to dotnet.

Then I re-read the hooks documentation, realized my hooks were in wrong place, moved them up a level, and the error message went away.

You're welcome to close this as a "won't fix", just want to make sure the error message is in the tracker for others to find who make the same mistake.

**Environment**

VS Code Details-
Version: 1.77.0-insider (Universal)
Commit: b9226e1ccc11625bcb42b55efb795e07ee533bb0
Date: 2023-03-24T18:44:58.328Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
