### ISSUE TITLE
Exit status 126 error when running hook bash script

### ISSUE THREAD

**Issue by rmeshksar** [Azure/azure-dev#1809]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
**azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)**

**Describe the bug**
When I run a simple bash script in predeploy (or any other hook) I get exit status 126 error code.

**To Reproduce**
This is my azure.yaml file:
```
name: my-app
services:
  api:
    project: src/api
    dist: build
    language: csharp
    host: containerapp
    module: app/api
    docker:
      path: ./Dockerfile
      context: ../
    hooks:
      predeploy:
        run: ../../infra/scripts/my-script.sh
        continueOnError: false
        interactive: false
```

and this is the content of  [root]/infra/scripts/my-script.sh file:

```
#!/bin/sh
echo "Running Script..."
```

And when I run 
```
azd deploy --service api --debug
```

I see the following error:

```
Executing predeploy hook => ../../infra/scripts/my-script.sh
2023/03/28 09:16:53 hooks_runner.go:145: Executing script '../../infra/scripts/my-script.sh'
2023/03/28 09:16:53 command_runner.go:88: Run exec: ' ../../infra/scripts/my-script.sh'
  (✓) Done: Deploying service api

ERROR: deploying service: failed invoking event handlers for 'predeploy', 'predeploy' hook failed with exit code: '126', Path: '../../infra/scripts/my-script.sh'. : exit status 126
```

**Comment by rmeshksar** [comment]
Thank you so much, it worked. 
```
name: my-app
services:
  api:
    project: src/api
    dist: build
    language: csharp
    host: containerapp
    module: app/api
    docker:
      path: ./Dockerfile
      context: ../
    hooks:
      predeploy:
        shell: sh
        run: chmod +x ../../infra/scripts/my-script.sh       <--------------
        continueOnError: false
        interactive: false
```
