### ISSUE TITLE
`panic` when `postpackage` hook fails

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1851]
```
$ azd version
azd version 0.7.0-beta.2-daily.2671790 (commit 23cf941b3e934e2f51606d467041e892d49e65bd)
```

Reproduce:

1. `azd init` and pick your favorite template
2. Add a hook that always fails. Example below:
```yaml
  api:
    project: ./src/api
    language: csharp
    host: appservice
    hooks:
      postpackage:
        shell: pwsh
        run: Write-Error "failing"; exit 1
        continueOnError: false
        interactive: false
```
3. Run `azd package`

Expected: hook fails with error "postpackage failed"
Actual: hook fails with the following error:

```
panic: Task result has already been set! Task cannot have both a result and an error.

goroutine 87 [running]:
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskContext[...]).SetError(...)
        D:/a/_work/1/s/cli/azd/pkg/async/task_context.go:23
github.com/azure/azure-dev/cli/azd/pkg/project.(*serviceManager).Package.func1(0xc0000f0c90)
        D:/a/_work/1/s/cli/azd/pkg/project/service_manager.go:356 +0x6fe
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskWithProgress[...]).Run.func1()
        D:/a/_work/1/s/cli/azd/pkg/async/task.go:144 +0x11d
created by github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskWithProgress[...]).Run
        D:/a/_work/1/s/cli/azd/pkg/async/task.go:140 +0x1cf
```

![image](https://user-images.githubusercontent.com/2322434/229606833-39d069b4-f178-4451-afb5-13df32852f52.png)
