### ISSUE TITLE
[Feature] Support a Docker only build strategy without specifying a language

### ISSUE THREAD

**Issue by sabbour** [Azure/azure-dev#1891]
Today, it looks like the `language` property is required. For builds that are purely `docker build` that deploy the containers on targets like `containerapps` and `aks`, why does this even matter? I don't want to have the build dependencies on my machine. This should also open up supporting any project as long as a Dockerfile exists.

```
services:
    frontend:
        project: ./src/frontend/code
        language: js # why do we need this?
        host: aks 
        k8s:
          deploymentPath: ../manifests
```
