### ISSUE TITLE
[SWA] Add support for swa-cli.config.json

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1953]
For deploying to `SWA` , azd takes the place of the classic SWA-CI-job which automatically builds the static web and publish it to Azure Static Apps.

When defining a service on `azd`, the path `./build` within the service path is used by default to create the static app package.
azd expects that the package operation will be placing the static page (html+js) into the build folder, where azd will take it and send it to Azure SWA.

Customers can change the `build` folder by adding `dist: path` to the azure.yml configuration, to define a different folder where the package is created.

However, there's not a way to tell `azd` what folder to use to package each language.  
In case of .NET, azd calls `dotnet publish` to produce the application package, but dotnet uses `/temp/xxxx` to place the output, and not a folder within `app/build`.  This means that as a customer, I can't set the `dist` value, as it will be different every time that the app is packaged.

For `dotnet` projects, there should be a way to set the output from `dotnet publish` so it can be deterministic and it can be set in the `dist` property from azure.yml.
Or, even better, for dotnet projects, azd should use the path from `/temp/xxx` where the application is placed by dotnet and use it for deployment.

The current workaround to make this work is to set a `prepackage` hook and call `dotnet publish -o some-path` and then set `dist: some-path`.
This will be making azd to call `dotnet publish` twice.  The first time from the hook, with a deterministic path to used later for deployment, and a second time while azd does `package` for dotnet, which will ended up in some /temp/xxx folder and ignored for deployment.

Example:

```yml
services:
  frontend:
    project: ./app/frontend
    host: staticwebapp
    dist: ./build/wwwroot
    hooks:
      prepackage:
        shell: pwsh
        run: dotnet publish -o build
        continueOnError: false
        interactive: true
```

Sample repo: https://github.com/vhvb1989/net-blazor-swa
