### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by pakbaz** [Azure/azure-dev#1964]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)

**Describe the bug**
trying to add pipeline for the repository https://github.com/Azure-Samples/azure-search-openai-demo 
running `azd pipeline config` with different combinations of providers and settings fails. not sure they have the correct base template setup or what is the issue? 

**To Reproduce**
the most recent failure. I download the code pushed it to azure devops and I use the following:

```bash
azd pipeline config --principal-name azdo --provider azdo -e azdopenai --debug
```

I have following configured in azd environment:

```
AZD_PIPELINE_PROVIDER="azdo"
AZURE_DEVOPS_ORG_NAME="xx"
AZURE_DEVOPS_PROJECT_ID="xxxxxx"
AZURE_DEVOPS_PROJECT_NAME="xxxx"
AZURE_DEVOPS_REPOSITORY_ID="xxxx"
AZURE_DEVOPS_REPOSITORY_NAME="xxxx"
AZURE_DEVOPS_REPOSITORY_WEB_URL="xxxx"
```

I run , it asks for PAT , I provide that (with full access) it asks: (Would you like to commit and push your local changes to start the configured CI pipeline? (Y/n)) and I Type Y+Enter and I get the following error:

  (✓) Done: Pushing changes
  (x) Failed: Queuing pipeline

ERROR: post git push hook: Could not queue the build because there were validation errors or warnings.

No pipeline is generated and nothing has been pushed.

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
Service Principal is correctly created/used and Azure DevOps Service connection is created and works but pipeline won't be generated. This is the Azure.yaml

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run:  cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
hooks:
    postprovision:
      windows:
        shell: pwsh
        run: ./scripts/prepdocs.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/prepdocs.sh
        interactive: true
        continueOnError: false

```
