### ISSUE TITLE
Segmentation error using invalid `host` for azure.yaml

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2025]
I was trying to test `springapp` as host and had a typo adding

```
api:
    project: ./src/api
    language: java
    host: springapps
```

This make azd to throw a panic like:

![image](https://user-images.githubusercontent.com/24213737/234367385-668e1b2a-7636-4808-baec-0cdb874b2ee0.png)

azd should not panic.  it should return an error and tell customer about the invalid value found.

At the very least, the panic should contain a message about the incorrect value.
