### ISSUE TITLE
"needs triage" is not being reliably removed once other tags are added

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2210]
Didn't we have a bot for that?

**Comment by vhvb1989** [comment]
We have the rule:

```yaml
    - if:
      - payloadType: Issues
      - isAction:
          action: Labeled
      - hasLabel:
          label: needs-triage
      - not:
          labelAdded:
            label: needs-triage
      then:
      - removeLabel:
          label: needs-triage
```

It should take care of removing the `needs-triage` as soon as any other tag is added.  I will create an issue to test it
