### ISSUE TITLE
[bug] azure.yaml schema says default shell is "sh" but error says otherwise

### ISSUE THREAD

**Issue by heaths** [Azure/azure-dev#2346]
The _azure.yaml.json_ schema says that the default `shell` is "sh", but if you don't specify it, something like the following errors:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/azure-dev-cli_1.0.1/schemas/v1.0/azure.yaml.json
name: azd
hooks:
  postprovision:
    run: |
      env
```
> ERROR: failed running post hooks: failed running scripts for hooks 'provision', hook configuration for 'postprovision' is invalid, unable to determine script type. Ensure 'Shell' parameter is set in configuration options
