### ISSUE TITLE
[feat] requiredVersions should allow az, bicep versions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-dev#2350]
Because `azd` relies at least on `bicep` but also fairly close with `az`, it would be great to be able to specify either of their version requirements in `requiredVersions` within _azure.yaml_. In my scenario, I need to make sure a specific version of `az` is installed or a command will not be defined as needed.

**Comment by vhvb1989** [comment]
@savannahostrowski do we have plans for defining external-dependencies per template/project?

@heaths, what command are you using which depends on `az` ?

**Comment by heaths** [comment]
See https://github.com/heaths/azcrypto/blob/963866f0eb9c0c1b5b10147deab1fab627929aec/azure.yaml#L21. Using `azd` for Managed HSM deployment requires a fairly recent `az` that at least supports https://github.com/heaths/azcrypto/blob/963866f0eb9c0c1b5b10147deab1fab627929aec/azure.yaml#L18. The other command is handy because then I can keep my key provisioning definitions consistent across Key Vault and Managed HSM: https://github.com/heaths/azcrypto/blob/963866f0eb9c0c1b5b10147deab1fab627929aec/infra/keys.bicep

If we ever were to replace parts of our `New-TestResources.ps1` script we use for cross-language test resource provisioning with `azd`, this is how I'd do it as well. Less duplication and maintenance hassles than creating keys via script commands instead.

In general, this really is more of an external dependency situation, but given there's a set of commands that `azd` uses e.g., `bicep`, or used to use e.g., `az` - of which we're still associated by nature, IMO - maybe we could at least support a subset of useful commands because we inherently know how to get version information from them, which is more of a problem in general.

**Comment by savannahostrowski** [comment]
I think there's probably an entire "tool" scenario that we don't support in azure.yaml today. I'd like to think more about what other things we'd want to handle here.

**Comment by heaths** [comment]
With a fixed set of tools you'd know the way to get and parse the version. Perhaps there's a known set you support OOBE, but could consider supporting any say, that an _azure.yaml_ could use in a script, by allowing users to add some schema e.g.:

```yaml
requiredVersions:
  az: '>= 2.24.0'
  azd: '>= 1.0.1'
  gh:
    info: https://github.com/cli/cli/releases/tag/v2.30.0 # alternatively, `run` if the app has a cross-plat run script
    check: gh --version
    checkPattern: 'gh version (\w+\.\w+\.\w+)' # version required in named capture or $1; expects semver
    require: '>= 2.28.0'
```

This is a rudimentary version of what we did for external packages in VS Setup. Though, to be clear, I was mainly thinking about common first-party apps e.g., `az`, or common partner apps e.g., `gh` (GitHub CLI) initially, if not forever.
