### ISSUE TITLE
[Issue] Azure functions runtime is unreachable

### ISSUE THREAD

**Issue by rachaelsingleton** [Azure/azure-dev#2376]
- [X ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
```azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)```

**Describe the bug**
I am able to successfully deploy my app containing a containerapp and function the first time via azd up. 
When making edits to the code and redeploying via azd deploy or azd up, the function app stops working. 
I get "Azure functions runtime is unreachable" in the Azure portal when viewing the function, and 500 when testing via postman. 

**To Reproduce**
azure.yml: 
```
name: myapp
services:
  app:
    language: python
    project: ./app
    host: containerapp
  batch: 
    project: ./app
    language: py
    host: function
```

**Expected behavior**
A working function app with updated code

**Environment**
Information on your environment:
    * Python
    * Visual Studio Code 1.78.2
