### ISSUE TITLE
`azd down` should purge App Configuration Service

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#248]
**Output from `azd version`**
`azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)`

**Output from `az version`** 
```js
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.5",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.2"
  }
}
```

**Describe the bug**
After running `azd down --force --purge --no-prompt` I'm finding that the "Azure App Configuration Service" resource was not purged.

**To Reproduce**
1. add an Azure App Configuration Service as a bicep resource
```
resource appConfigSvc 'Microsoft.AppConfiguration/configurationStores@2022-05-01' = {
  name: '${resourceToken}-appconfig'
  location: location
  sku: {
    name: 'Standard'
  }
}
```
3. `azd provision --no-prompt`
4. `azd down --force --purge --no-prompt`

**Expected behavior**
Expected the same behavior as provided for Key Vault so I can use `azd` in a nightly build that will create and then tear down resources without conflict.

**Environment**
- azd runs from GH workflow
```
      - name: Azure Dev Down
        run: azd down --force --purge --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_NIGHTLY_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

**Additional context**
Can work around the issue with a deployment script. Something like...

*yourScriptName.sh*
```sh
deletedAppConfigSvc=$(az appconfig list-deleted --query "[?starts_with(name, '$resourceToken')].name" -o tsv)

if [[ ${#deletedAppConfigSvc} -gt 0 ]]; then
  az appconfig purge --name $deletedAppConfigSvc --yes
else
  echo "Nothing to purge"
fi
```

*bicep resource*
```
resource app_config_svc_purge 'Microsoft.Resources/deploymentScripts@2020-10-01' = {
  name: 'app_config_svc_purge'
  location: location
  kind:'AzureCLI'
  properties: {
    azCliVersion: '2.37.0'
    retentionInterval: 'P1D'
    scriptContent: loadTextContent('yourScriptName.sh')
    arguments:'--resourceToken \'${resourceToken}\''
  }
}
```
