### ISSUE TITLE
add Azure DevOps Task(setup-azd) to todo templates

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2642]
Task
- Update todo templates to consume Azure DevOps Task(setup-azd) - https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd
- Remove references to usage of `auth.useAzCliAuth` from [azdo pipelines](https://github.com/search?q=repo%3AAzure%2Fazure-dev+auth.useAzCliAuth+language%3AYAML&type=code&l=YAML)
- File issues on awesome-azd templates containing azdo pipelines to consume Azure DevOps Task(setup-azd) - https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd

Reference - Similar to GHA setup-azd updates,
- https://github.com/marketplace/actions/setup-azd
- https://github.com/Azure/azure-dev/pull/2462

cc: @hemarina @vhvb1989

**Comment by vhvb1989** [comment]
setupt-azd task for azdo is not a built-in extension. 
Folks first need to install the extension within their devops org.

If we update our todo-templates, we need to add a note to the readme files about installing the extension before using the pipeline definition.

**Comment by zedy-wj** [comment]
@vhvb1989 - When we try to remove references to usage of `auth.useAzCliAuth` from [azdo pipelines](https://github.com/search?q=repo%3AAzure%2Fazure-dev+auth.useAzCliAuth+language%3AYAML&type=code&l=YAML), it seems that we need `azd auth login` step to replace it. 
How do we configure relevant credentials, similar to that in github workflow as below:
![image](https://github.com/Azure/azure-dev/assets/81678720/0c8fb0e0-e697-47ad-8523-77bd6ead00df)

**Comment by vhvb1989** [comment]
Thank you @zedy-wj ,

We first need this PR: https://github.com/Azure/azure-dev/pull/2667
That would set the `AZURE_CREDENTIALS` secret the same way as github actions.
Note that we don't have support for `federated-credential` on azdo. Azd automatically changes to `client-secret` authentication when using azdo.

Once the PR is merged, the pipeline definition should look like:

```yml
# Run when commits are pushed to mainline branch (main or master)
# Set this to the mainline branch you are using
trigger:
  - main
  - master

# Azure Pipelines workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config --provider azdo`

pool:
  vmImage: ubuntu-latest

steps:
  - task: setup-azd@0
    displayName: Install azd

  - pwsh: |
      $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
      
      azd auth login `
        --client-id "$($info.clientId)" `
        --client-secret "$($info.clientSecret)" `
        --tenant-id "$($info.tenantId)"
    displayName: azd login
    env:
      AZURE_CREDENTIALS: $(AZURE_CREDENTIALS)

  - pwsh: |
      azd provision --no-prompt
    displayName: Provision Infrastructure
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)

  - pwsh: |
      azd deploy --no-prompt
    displayName: Deploy Application
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)

```
