### ISSUE TITLE
[Feature] Support for deploying App Container Jobs

### ISSUE THREAD

**Issue by Digma** [Azure/azure-dev#2743]
It is not possible to deploy App Container Jobs (Microsoft.App/jobs, [Container App jobs](https://learn.microsoft.com/en-us/azure/container-apps/jobs)) with `azd deploy`

**Output from `azd version`**

> ERROR: failed deploying service 'SERVICE_NAME': failing invoking action 'deploy', validating target resource: resource 'CONTAINER_APP_JOB_NAME' with type 'Microsoft.App/jobs' does not match expected resource type 'Microsoft.App/containerApps'

**Describe the bug**
We are building some container jobs to consume and process events from AzureEventGrid. Container Jobs seem great for that but unfortunately, the deployment of containers is not supported today by `azd` without workarounds

**To Reproduce**
Create a 'Microsoft.App/jobs' resource and try to deploy an docker image with `azd deploy` (azure.yml, is configured as `host: containerapp`)

**Expected behavior**
It is possible to deploy to container app jobs using `azd deploy`, potentially by specifying a different host in `azure.yml`

**Comment by ellismg** [comment]
Similar to #2665.  Interested in what other workflow you might have around this, @Digma?  Would you expect a way to run the job via `azd`?  Do you have some other strategy for invoking them (i.e. perhaps they are doing background work for an app and launched by your app itself)

**Comment by Digma** [comment]
Indeed similar to #2665. It sems my search missed it. Feel free to close if this is a duplicate

In general, we like working with containers for our different apps and pipelines. For that example, we have some file processing pipeline which is triggered by a queue linked with events on a blob storage (EventGrid). Given files do not get updated all the time, the container app job allow us to easily run only when needed (when there are events in the queue).

**Comment by ianphil** [comment]
This would be useful for me also. I think keeping `host: containerapp` and this host type supports jobs. Just my 2c...

**Comment by karpikpl** [comment]
It would be great if jobs were supported.
common pattern fort short lived containers and having it done by AZD would make creating demos/POCs much easier

**Comment by amgdy** [comment]
Hi team, do you have any updates on when this feature might be added? Are there any workarounds available now to include a container app job as a service?

**Comment by amgdy** [comment]
> Hi team, do you have any updates on when this feature might be added? Are there any workarounds available now to include a container app job as a service?

As a workaround, I used the `postprovision` hook to run a script to build and push container to the ACR then update the container app job with the new image, and I disabled/removed the `services` section until the feature is available.

Here is the relevant section from my `azure.yaml`:

```yaml
name: azure-ai-search-website-crawler
metadata:
    template: azd-init@1.11.0

hooks:
    postprovision:
        windows:
            shell: pwsh
            continueOnError: false
            interactive: true
            run: ./scripts/Deploy-AzureContainerAppJob.ps1
        posix:
            shell: sh
            continueOnError: false
            interactive: true
            run: ./scripts/deploy-azure-container-app-job.sh
```
You can view [`azure.yaml`](https://github.com/amgdy/azure-ai-search-website-crawler/blob/main/azure.yaml), [`deploy-azure-container-app-job.sh`](https://github.com/amgdy/azure-ai-search-website-crawler/blob/main/scripts/deploy-azure-container-app-job.sh) and [`Deploy-AzureContainerAppJob.ps1`](https://github.com/amgdy/azure-ai-search-website-crawler/blob/main/scripts/Deploy-AzureContainerAppJob.ps1) for more details.
