### ISSUE TITLE
[Issue] 403 error when listing environments with remote environments enabled

### ISSUE THREAD

**Issue by bwateratmsft** [Azure/azure-dev#2790]
Installed the PR build from https://github.com/Azure/azure-dev/pull/2765.

Enabled remote environments with azure.yaml:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/54bcf14fcf51640c867025447732b14c2493e892/schemas/alpha/azure.yaml.json

name: todo-csharp-cosmos-sql
metadata:
  template: todo-csharp-cosmos-sql@0.0.1-beta
services:
  web:
    project: ./src/web
    dist: build
    language: js
    host: appservice
  api:
    project: ./src/api
    language: csharp
    host: appservice
state:
  remote:
    backend: AzureStorage
    config:
      accountName: redacted
```

```
PS D:\Sandbox\EmptyProj> azd env list

ERROR: listing environments: retrieving remote environments, listing blobs: failed to get next page of blobs, GET https://redacted.blob.core.windows.net/todo-csharp-cosmos-sql
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is nnot authorized to perform this operation using this permission.
RequestId:a7219304-801e-0068-78ad-f0866e000000
Time:2023-09-26T19:15:47.6046120Z</Message></Error>
--------------------------------------------------------------------------------
```
