### ISSUE TITLE
[package] allow to choose when build/packaging step occurs in the lifecycle

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-dev#2850]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
```
azd version
azd version 1.4.1 (commit 1cbed85cf47ed235b5ed31868eda79619525bfcc)
```

**Describe the issue**
In microservices architectures where the frontend is deployed as a separate component, you need to get the backend/API location after the provisioning as the backend URL need to be provided at build time for static web apps.

We have the case for example in https://github.com/Azure-Samples/contoso-real-estate and https://github.com/Azure-Samples/azure-search-openai-javascript.

In the first sample, `azd up` cannot be used because of this, and it needs to run `azd provision` then `azd deploy` as a workaround.

In the second sample, we used a different workaround so that `azd up` could be used: we added a "predeploy" script to build the app just before deployment, but that effectively cause the app to be built twice.

This is a very common use case and it feels hacky to have to make twists like these to make it work.

Would it be possible to consider a `step` property under a `build` or `package` settings to define when the command should be ran? For example:

```yaml
services:
  webapp:
    project: ./packages/webapp
    dist: dist
    language: ts
    host: staticwebapp
    package:
      step: predeploy
```
