### ISSUE TITLE
[Question] How do I show the web service endpoint before `azd deploy`?

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-dev#2884]
## Question

When I run `azd up` or `azd deploy`, the CLI outputs the URL of the deployed web application. I have scenarios where I want to run `azd provision` but not run `azd deploy` but still would like the URL of the deployed site. 

Is there a command in the CLI (ex. `azd ___ show ____`) to just show the target web application endpoint without deploying?

## Context

I'm working on a basic AZD template that deploys a containerized .NET 8 web application to Azure Container Apps with Azure Cosmos DB as the backing database. The source code is here, but it's changing constantly:

https://github.com/Azure-Samples/cosmos-db-nosql-dotnet-quickstart

I anticipate that I will use the Azure Cloud Shell to run `azd provision` and an IDE like GitHub Codespaces to run `azd deploy` or `azd up`. To handle this, I have the repo setup to prebuild the application's container image and then deploy that to the container app as part of `azd provision`:

| | Link |
| --- | --- |
| **Prebuilt container image** | <https://github.com/Azure-Samples/cosmos-db-nosql-dotnet-quickstart/pkgs/container/cosmos-db-nosql-dotnet-quickstart> |
| **Bicep deploy default container image** | <https://github.com/Azure-Samples/cosmos-db-nosql-dotnet-quickstart/blob/main/infra/app/web.bicep#L33> |

So, if you run `azd provision` the application will "just work" with the latest build from the primary branch. This is designed to work in Azure Cloud Shell which has no Docker host.

You can then modify the code in an IDE with a Docker host and run `azd deploy` or `azd up` to deploy your changes.

## Ideal scenario

1. Init the template using `azd init --template cosmos-db-nosql-dotnet-quickstart`
1. Deploy the infrastructure using `azd provision` (this deploys pre-baked container image)
1. <ins>Run some command to see container app endpoint (???)</ins> *:triangular_flag_on_post: This is what I can't figure out*
1. View running and working application
1. Change something in the code
1. Deploy your changes with `azd deploy` or `azd up`

**Comment by savannahostrowski** [comment]
@seesharprun We are working on https://github.com/Azure/azure-dev/issues/1887 right now but this doesn't cover the scenario you're describing (e.g. just the provision scenario)...@gkulin @ellismg Thoughts here?

**Comment by seesharprun** [comment]
@savannahostrowski, I searched but didn't find that issue, thanks for linking!

It looks to me like `azd show` would cover my scenario fine because it shows the web application's endpoint (my end goal here).

I figured out the other moving parts.

**Comment by savannahostrowski** [comment]
I think that this would only show deployed endpoints but @gkulin can confirm...not sure what the behaviour would look like if the application was only provisioned.

**Comment by seesharprun** [comment]
Thanks for that clarification. I'll wait for the rest of your team's thoughts.

**Comment by jongio** [comment]
@seesharprun - You can do this with a hook:

azure.yaml
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: todo-python-mongo
metadata:
  template: todo-python-mongo@0.0.1-beta
services:
  web:
    project: ./src/web
    dist: build
    language: js
    host: appservice
  api:
    project: ./src/api
    language: py
    host: appservice
hooks:
  postprovision:
    windows:
      run: Write-Output "$env:SERVICE_WEB_ENDPOINT / $env:SERVICE_API_ENDPOINT"
      shell: pwsh
      continueOnError: false
      interactive: true
    posix:
      run: echo $SERVICE_WEB_ENDPOINT / $SERVICE_API_ENDPOINT
      shell: sh
      continueOnError: false
      interactive: true
```

main.bicep
```
output SERVICE_WEB_ENDPOINT string = web.outputs.SERVICE_WEB_URI
output SERVICE_API_ENDPOINT string = api.outputs.SERVICE_API_URI
```

Which will output this:
<img width="501" alt="image" src="https://github.com/Azure/azure-dev/assets/2163001/737f1985-388b-48d2-959b-d1d0c9b7521d">

The bicep outputs are stored as environment variables that are available in hooks.  So you just need to output what you need in bicep and then echo that in a hook.

The above `echo` is a simple one, you can put whatever text you want there and you can also put that in a script file instead of inline.  Here's the doc on it https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility

Reach out if you need help.
