### ISSUE TITLE
.NET project build with dependencies fails

### ISSUE THREAD

**Issue by ngruson** [Azure/azure-dev#2915]
I'm trying to deploy my .NET 7 solution to Azure using Azure Developer CLI.

Azure.yaml:
```yaml
name: myapp
metadata:
    template: azd-init@1.4.3
services:
    MyApp.Api:
        project: src\Api\MyApp.Api
        host: containerapp
        language: dotnet
```

The API project has several dependencies to class libraries which are also contained in the Visual Studio solution.
For example:
```xml
<ProjectReference Include="..\MyApp.Core\MyApp.Core.csproj" />
```

When i run `azd up`, the build of the API starts which ultimately fails.
It seems that the class library projects are not copied to the build container.
The error from the build logs:
```
[builder]   Determining projects to restore...
[builder]   Skipping project "/MyApp.Core/MyApp.Core.csproj" because it was not found.

[builder] /layers/opt/dotnet/7.0.306/sdk/7.0.306/Microsoft.Common.CurrentVersion.targets(2116,5): warning : The referenced project '../MyApp.Core/MyApp.Core.csproj' does not exist.
```
How do I fix this and make sure that the other C# projects are available in the build container?
