### ISSUE TITLE
Ingress in Aspire generated internal Container App should have AllowInsecure: true

### ISSUE THREAD

**Issue by julioct** [Azure/azure-dev#3021]
**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
In an Aspire app a frontend usually needs to call the backend, using urls like this:

http://backend

There's no need for HTTPS since the backend is only visible to the frontend and TLS terminates on the ingress service.

However, this configuration won't work by default because the ingress for all container apps provisioned by Aspire seems to not allow insecure communication between them:

```yaml
properties:
  configuration:
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: false
```

Notice the `allowInsecure:false` setting.

This setting should be true if the ingress is not external (external: false) as in the example above.

**To Reproduce**
1. md aspire02

2. cd aspire02

1. dotnet new aspire-starter

2. azd init

4. Ensure only the Web frontend project is exposed to Internet

5. azd config set alpha.infraSynth on

6. azd infra synth

8. Open **containerApp.tmpl.yaml** under aspire02\ApiService\manifests

9. Notice the value of `external` and `allowInsecure` under ingress:

```yaml
properties:
  configuration:
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: false
```

**Expected behavior**
The ingress section in the generated yaml for ApiService should have `allowInsecure:true`, look like this:

```yaml
properties:
  configuration:
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
```

**Environment**
Information on your environment:
    * English. Windows_NT x64 10.0.22621.
    * VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
