### ISSUE TITLE
[Issue] AzDO hosted images do not have setup-azd pre-installed

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3030]
The default Azure Pipelines yaml definition that comes with most delivered templates from Azure team includes the `setup-azd` task.  This is currently not a part of the base images so unless you have full admin permissions on the AzDO org instance, it would be a stop-gap to get it installed in the organization.

Consider getting this into some more base definition so it isn't a speedbump in configuring AzDO

**Comment by vhvb1989** [comment]
When azd auto-generates the azdo pipeline template, it provides a comment about what to do if people can use/install the setup-azd :

```yaml
steps:
  # setup-azd@1 needs to be manually installed in your organization
  # if you can't install it, you can use the below bash script to install azd
  # and remove this step
  - task: setup-azd@1
    displayName: Install azd

  # If you can't install above task in your organization, you can comment it and uncomment below task to install azd
  # - task: Bash@3
  #   displayName: Install azd
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       curl -fsSL https://aka.ms/install-azd.sh | bash
```
