### ISSUE TITLE
[Issue] Deploy Aspire into Azure

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-dev#3098]
Im trying to deply my Aspire app into azure, and as result I see this error:
```

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

|       | 
|=      | 
|       | 
|=      | 
|       | 
|=      | 
Subscription: Microsoft Azure Sponsorship
Location: West Europe

|       | 
|=      | 
|==     | 
|===    | 
  (-) Skipped: Didn't find new changes.


Deploying services (azd deploy)

|       | 
|=      | 
|==     | 
|===    | 
|====   | 
|=====  | 
|====== | 
panic: send on closed channel

goroutine 91 [running]:
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskContextWithProgress[...]).SetProgress(...)
	/mnt/vss/_work/1/s/cli/azd/pkg/async/task_context.go:67
github.com/azure/azure-dev/cli/azd/pkg/project.syncProgress[...](0xc00063b8c0, 0xc000642f98)
	/mnt/vss/_work/1/s/cli/azd/pkg/project/service_manager.go:656 +0xbd
created by github.com/azure/azure-dev/cli/azd/pkg/project.runCommand[...].func1 in goroutine 87
	/mnt/vss/_work/1/s/cli/azd/pkg/project/service_manager.go:636 +0xb9
##[error]Script failed with exit code: 2
/usr/bin/az account clear
```
but resourses are created.

or like this
```
Deploying services (azd deploy)

|       | 
|=      | 
|==     | 
|===    | 
|====   | 
|=====  | 
|====== | 
|=======| 
| ======| 
|  =====| 
  (x) Failed: Deploying service api

ERROR: failed deploying service 'api': failing invoking action 'deploy', failed executing template file: template: containerApp.tmpl.yaml:1:17: executing "containerApp.tmpl.yaml" at <.Env.AZURE_LOCATION>: map has no entry for key "AZURE_LOCATION"
```
in this case I have repostiry in ACR.

and in my pipeline I have 
```
  - task: AzureCLI@2
    displayName: "Deploy Application"
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_LOCATION: $(AZURE_LOCATION)
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      useGlobalConfig: true
      inlineScript: |
        azd deploy --no-prompt
```

or like this 
```
Deploying services (azd deploy)

|       | 
|=      | 
|==     | 
|===    | 
|====   | 
|=====  | 
|====== | 
panic: send on closed channel

goroutine 55 [running]:
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskContextWithProgress[...]).SetProgress(...)
	/mnt/vss/_work/1/s/cli/azd/pkg/async/task_context.go:67
github.com/azure/azure-dev/cli/azd/pkg/project.syncProgress[...](0xc00014e750, 0x0)
	/mnt/vss/_work/1/s/cli/azd/pkg/project/service_manager.go:656 +0xbd
created by github.com/azure/azure-dev/cli/azd/pkg/project.runCommand[...].func1 in goroutine 29
	/mnt/vss/_work/1/s/cli/azd/pkg/project/service_manager.go:636 +0xb9
```

**Comment by vhvb1989** [comment]
This issue is fixed here: https://github.com/Azure/azure-dev/issues/3031

But it is not yet part of latest release.
You can try installing azd-daily from your pipeline definition, using:

```
  - task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily
```

Use that script instead of `task: setup-azd@0 ` , which pull the latest release version.

The next azd release is scheduled for next week ~12/12, once it is released, you can switch your pipeline to use `task: setup-azd@0 ` again.

There are currently a few fixes for Aspire on daily build.
