### ISSUE TITLE
Ability to override CLI commands for individual app projects

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#312]
As part of the CLI extensibility it would be great if an app dev that is dev-ifying their app can override the default commands.

## Initial use case
Application has custom build requirements that we would not be able to discover

## How would it work?
**Convention based**
App devs can create their own `.azure` folder with the `project` folder location
- App dev creates a `build.sh` or `build.ps1` file
- CLI detects this file exists and overrides the default `build` command

**Configuration based**
- App dev adds additional markup in the `azure.yml`
- Something similar to the `scripts` section in node apps.
- App dev add configuration to call the right script

Would also be great to support `pre` and `post` command scripts.

```yaml

# azure.yaml
...
services:
  api:
    project: src/api
    language: js
    host: appservice
    scripts:
      build: custom-build.sh
```
