### ISSUE TITLE
[buildpacks] unable to build .NET projects with sibiling reference projects

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#3124]
Repro:
1. Have a project directory like: `./App/App.csproj` that references `./lib/Library.csproj`. Don't provide any Dockerfiles.
2. Have `azure.yaml` (run `azd init` to bootstrap if needed) that looks like:
```yaml
services:
  app:
    project: ./App
    host: containerapp
    language: dotnet
```
3. Run `azd package` / `azd up`

Expected:
`azd package`/ `azd up` succeeds

Actual:
Command fails with `The referenced project '../lib/Library.csproj' does not exist. [/workspace/App.csproj]`
