### ISSUE TITLE
Latest azd can't deploy manifests with a connection string reference

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#3126]
Not sure if this is a timeout issue but I hit it trying to deploy an application:

  | ======| Deploying service myblogapi (Pushing container image)panic: send on closed channel

```
goroutine 192 [running]:
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskContextWithProgress[...]).SetProgress(...)
        github.com/azure/azure-dev/cli/azd/pkg/async/task_context.go:67
github.com/azure/azure-dev/cli/azd/pkg/project.syncProgress[...](0xc000294630, 0x4f3363444d695244)
        github.com/azure/azure-dev/cli/azd/pkg/project/service_manager.go:657 +0xbd
created by github.com/azure/azure-dev/cli/azd/pkg/project.runCommand[...].func1 in goroutine 64
        github.com/azure/azure-dev/cli/azd/pkg/project/service_manager.go:637 +0xb9
```

Ran azd again and hit this:

```
  (x) Failed: Deploying service myblogapi

ERROR: failed deploying service 'myblogapi': failing invoking action 'deploy', failing parsing containerApp.tmpl.yaml: template: containerApp.tmpl.yaml:27: unexpected "\\" in operand
```

The app is using preview1 of aspire and the latest azd.

azd version:

```
azd version 1.5.1-daily.3344560 (commit db367006177b2264d05cfbc390ca7c94a1314c97)
```

Manifest:

```JSON
{
  "resources": {
    "pg": {
      "type": "postgres.server.v0"
    },
    "db": {
      "type": "postgres.database.v0",
      "parent": "pg"
    },
    "storage": {
      "type": "azure.storage.v0"
    },
    "blobs": {
      "type": "azure.storage.blob.v0",
      "parent": "storage"
    },
    "myblogapi": {
      "type": "project.v0",
      "path": "..\\MyBlog.Api\\MyBlog.Api.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "ConnectionStrings__db": "{db.connectionString}"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http"
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http"
        }
      }
    },
    "myblog": {
      "type": "project.v0",
      "path": "..\\MyBlog\\MyBlog.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "ConnectionStrings__blobs": "{blobs.connectionString}",
        "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true",
        "services__myblogapi__0": "{myblogapi.bindings.http.url}",
        "services__myblogapi__1": "{myblogapi.bindings.https.url}"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http"
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http"
        }
      }
    }
  }
}
```

Here's the template for the app that fails to deploy:

```yaml
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
    - image: {{ .Image }}
      name: myblogapi
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: ConnectionStrings__db
        value: "{{ connectionString \"db\" }}"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
    scale:
      minReplicas: 1
tags:
  azd-service-name: myblogapi
  aspire-resource-name: myblogapi
```

This seems to be the issue  

```
value: "{{ connectionString \"db\" }}"
```

Seems related to [this PR](https://github.com/Azure/azure-dev/commit/cb86a7d6b0a4956315f876bac32bc82c2f14ad08)

OK this fixed it:

```
value: {{ connectionString "db }}
```

The string for these golang template expressions shouldn't be wrapped in quotes 😄
