### ISSUE TITLE
[Issue] WithServiceBinding allow external: true for ingress

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-dev#3156]
azd 1.5.1

``` yaml
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: true
```

hello! is there a way to set ` external: true` from code? I think it will be good option.
for now I have to generate bicep and use `azd infra synth` and then modify it for specific service
