### ISSUE TITLE
`azd package` requires an environment name

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-dev#3182]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

`azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)`

**Describe the bug**
I want to use `azd package` as a "smoke test" in CI to ensure that the packages can be successfully built on each commit/push to a branch.

I've created a workflow like so:

```yaml
name: azd package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "feature/*"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

      - name: Package with azd
        run: azd package
```

But it errors when running because there's not environment name set, as showing by the repeated log message:

`Enter a new environment name: environment name '' is invalid (it should contain only alphanumeric characters and hyphens)`

Also, it keeps attempting to get the environment name, so I either have to kill the job or wait for it to time out. [Here's an example run](https://github.com/microsoft/azure-openai-service-proxy/actions/runs/7443285241/job/20247950633?pr=93).

**To Reproduce**
- Create a GitHub Actions workflow as above
- Push and run
- See the logs for GitHub Actions.

**Expected behavior**
Since I'm not deploying, I shouldn't need an environment name to run `azd package`.

**Environment**
GitHub Actions
