### ISSUE TITLE
[Issue] Unable to get environment name in azure.yaml

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-dev#3194]
**Output from `azd version`**
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the bug**

When creating resources in Azure, we use the environment as part of the naming convention i.e. `func-{productname}-{environmentName}-001`. Following this naming convention is possible as part of the infrastructure, but I am unable to get the environment name in the azure.yaml as part of the service name and therefore my deployment does not know the name of the resource to deploy to.

How do I get some sort of variable into the azure.yaml so the deployment can target the correct resource?

**Expected behavior**

In the azure.yaml, something like:

``` yaml
name: azure-openai-document
metadata:
  template: azure-openai-document@0.0.1-beta
services:
  func-azd1-{environmentName}-001:
    project: ./src/extract
    language: python
    host: function
```
I have added the `{environmentName}` as an example, and if this did work it would allow the provisioning to map to the `azd-service-name` tag on the resource.
