### ISSUE TITLE
Provide a way to write select bicep outputs to dotnet user-secrets for Aspire apps

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3202]
We are thinking about something like:

`@metdata({azd: { dotnetUserSecretsName: 'ConnectionStrings:foo' }})` 

On outputs meaning "put this in dotnet user-secrets with the given name".  Doing it this way instead of our existing dotnet method of adding every output (after normalization) to give users better control of the name and set of secrets that are added.

**Comment by ellismg** [comment]
Feels like similar machinery could be used for #3201 (perhaps a different key name in the metadata bag?)

**Comment by ellismg** [comment]
Thinking we would write these in the user-secrets of the AppHost itself, not the individual projects referenced by the app host.

**Comment by seesharprun** [comment]
I'm doing something similar using a `postprovision` script but it feels icky.

```yml
hooks:
  postprovision:
    windows:
      run: |
        dotnet user-secrets set "AZURE_COSMOS_DB_NOSQL_ENDPOINT" "$env:AZURE_COSMOS_ENDPOINT" --project ./src/api/Cosmos.Samples.NoSQL.Quickstart.Api.csproj
      shell: pwsh
      continueOnError: false
      interactive: true
    posix:
      run: |
        dotnet user-secrets set "AZURE_COSMOS_DB_NOSQL_ENDPOINT" "$AZURE_COSMOS_ENDPOINT" --project ./src/api/Cosmos.Samples.NoSQL.Quickstart.Api.csproj
      shell: sh
      continueOnError: false
      interactive: true
```
