### ISSUE TITLE
Support to reference multiple container projects

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3236]
When working with AKS it is very common to be composing multiple k8s resources that comprise of deployments, services, configuration & ingress to name a few.

If the intent is to build/package/push multiple containers these containers and their relevant source code will more easily be managed in the context of a single `azd` service.

Developers can utilize popular k8s deployment tools like Helm, Kustomize or raw yaml definitions to compose the resource definitions into a single atomic deployment command.

## Example
```yaml
# azure.yaml

name: todo-nodejs-mongo-aks
metadata:
  template: todo-nodejs-mongo-aks@0.0.1-beta
services:
  todo:
    host: aks
    # Manually specify the AKS cluster name to connect to already existing cluster (default: AZURE_AKS_CLUSTER_NAME)
    resourceName: aks-22mkcdyjkqce2
    # Manually specify the ACR registry to connect to already existing cluster (default: AZURE_CONTAINER_REGISTRY_ENDPOINT)
    docker:
      registry: cr22mkcdyjkqce2.azurecr.io
    # The containers that need to be built, packaged and deployed for this service
    containers:
      web:
        project: ./src/web
        dist: build
        language: js
      api:
        project: ./src/api
        language: js
    k8s:
      # The default namespace used in the kubeconfig file (default: ${project.name})
      namespace: todo
      # Whether or not the cluster kubeconfig should be merged into the main .kube/config file (default: true)
      mergeKubeConfig: false
      # Configure the helm releases to deploy for this AKS cluster
      helm:
        releases:
          - name: todo
            chart: ./charts/todo
            values:
              - ./charts/todo/${AZD_ENV_NAME}-values.tmpl.yaml
```
