### ISSUE TITLE
Add support to reference container registry in `azure.yaml`

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3238]
Today the container registry endpoint used for integration with AKS and container apps must be set in the `AZURE_CONTAINER_REGISTRY_ENDPOINT` environment variable.

In addition to this environment variable the container registry should also be settable in the `docker` options under `registry`.

## Example
```yaml
# azure.yaml

name: my-project
metadata:
  template: my-project@0.0.1-beta
services:
  api:
    project: ./src/api
    language: js
    host: containerapp
    docker: 
      registry: docker.io/wbreza
      repository: my-project
      tag: latest
```
