### ISSUE TITLE
Support for public/pre-built images for container based service targets

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3240]
## Proposal

Users can specify public or fully qualified image references as part of their container app configuration. In the following example a container app will be created using the public nginx image.

## Example

```yaml
# azure.yaml

name: my-project
metadata:
  template: my-project@0.0.1-beta
services:
  api:
    host: containerapp
    image: nginx
```
