### ISSUE TITLE
Support for 3rd party container registries

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3241]
### Optional registry and repository configuration elements within docker
Each container configuration element will allow a registry and repository configurations within the docker options that will allow support for specifying the registry and repository that should be used for the container image when build.

If registry is not specified it will fall back to the `AZURE_CONTAINER_REGISTRY_ENDPOINT` environment variable specified within the azd environment.

If repository is not specified it will default a convention of `{project.name}-{service.name}`

ACR registries will be natively support and leverage the current logged in principal. To support 3rd party private registries users will need to ensure they run the docker login command with their credentials commands prior deploying from azd.

These options can be configured at the root of the conatainerapp or within each container depending on the application requirements.

## Example

The following example shows how a custom registry can be specified when using container apps.  In this example the container would be built and pushed to a private container registry on Docker Hub.

>[!NOTE]
> Users would need to ensure they are pre-authenticated into the Docker CLI to allow pushing to private sources.

```yaml
# azure.yaml

name: my-project
metadata:
  template: my-project@0.0.1-beta
services:
  api:
    project: ./src/api
    language: js
    host: containerapp
    docker: 
      registry: docker.io/wbreza
      repository: my-project
      tag: latest
```
