### ISSUE TITLE
[Issue] Deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription: In Azure i can see 502 (Bad Gateway) (Code: ValidationError, Target: representation)

### ISSUE THREAD

**Issue by Fariz-fx** [Azure/azure-dev#3350]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

We are using github action to perform deployment to dev environment in yml we use the below step

```yml
      - name: Install azd
        uses: Azure/setup-azd@v0.1.0
```

**Describe the bug**

We are performing github deployment where in azd provison step it failed, upon re-run it succeded we want to know the root cause for this issue

deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription: In Azure i can see 502 (Bad Gateway) (Code: ValidationError, Target: representation)

We are making use todopython fastapi azd template, on top of it we added our application code ( frontend static webapp in nextjs and backend Azure container app using fastapi) we have APIM and event grid in place

```yml
      - name: Azure Dev Provision
        if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.infra == 'true'
        run: |
          azd provision --no-prompt
```

Detailed error

```
(✓) Done: Resource group: rg-dev
(✓) Done: Key Vault: kv-abcdefg12345br
(✓) Done: Storage account: appnamedev
(✓) Done: Static Web App: userguide
(✓) Done: Static Web App: stapp-web-abcdefg12345br
(✓) Done: Static Web App: stapp-admin-abcdefg12345br
(✓) Done: Log Analytics workspace: log-abcdefg12345br
(✓) Done: Application Insights: appi-abcdefg12345br
(✓) Done: Portal dashboard: dash-abcdefg12345br
(✓) Done: Azure Cosmos DB: cosmos-abcdefg12345br
(✓) Done: Container Apps Environment: cae-abcdefg12345br
(✓) Done: Container Registry: crabcdefg12345br
(✓) Done: Container App: ca-api-abcdefg12345br
(✓) Done: Azure API Management: apim-abcdefg12345br

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ValidationError: One or more fields contain incorrect values:
ValidationError: Parsing error(s): Failed to import from specified resource https://ca-api-abcdefg12345br.redrock-2824fdf4.eastus2.azurecontainerapps.io/openapi.json: Response status code does not indicate success: 502 (Bad Gateway)..

TraceID: 1ccd4c048386307cc3c3484f033acb57
Error: Process completed with exit code 1.

```

**To Reproduce**

Ensure your container app not used and scaled to 0.
Run the Deploy to Dev github action ( i used todo python fastapi azd template)
At first time you can see it failed with above error, re-run will succeed.

**Expected behavior**
It should run successful and eploy properly to azure

**Environment**
Information on your environment:
    * Language name and version: Using Github action for deployment, Nextjs 13, Fastapi, Bicep (provided by azd)
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

We want to know the root cause for the same

**Comment by rajeshkamal5050** [comment]
@hemarina can you try reproducing this? cc @vhvb1989

**Comment by Fariz-fx** [comment]
> @Fariz-fx Could you share azure.yaml if possible?

Thanks for your help in advance, PFB, to reproduce ensure container app is scaled 0, at first it will fail, next run it will pass. Also it happened on Sept 2023, In recent times, we haven't encountered much still we want to know root cause for the same

```yaml
services:
  admin:
    project: ./src/admin
    dist: out
    module: app/admin
    language: ts
    host: staticwebapp
  web:
    project: ./src/web
    dist: out
    module: app/web
    language: ts
    host: staticwebapp
  api:
    project: ./src/api
    module: app/api
    language: python
    host: containerapp
```
