### ISSUE TITLE
ADE projects with `platform: deventer` should set platform configuration

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3366]
If platform type is set to `devcenter` in the azure.yaml then azd should automatically leverage all the devcenter platform components including provision provider.

```yaml
# azure.yaml

name: todo-nodejs-mongo-aca
metadata:
    template: todo-nodejs-mongo-aca@0.0.1-beta
services:
    api:
        project: ./src/api
        host: containerapp
        language: js
    web:
        project: ./src/web
        host: containerapp
        language: js
platform:
    type: devcenter # <- this should be enough to init devcenter mode
    config:
        catalog: Example
        environmentDefinition: XXX
        name: XXX
```

**Expected**
When devcenter is set in the azure.yaml, this should enable devcenter mode and provision via devcenter provision provider

**Actual**
Standard IaC (bicep) provision provider is invoked

**Workaround**
Set devcenter mode globally by running `azd config set platform.type devcenter`
