### ISSUE TITLE
Service hook `predeploy` does not work for appcontainer

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3546]
For example:

```yaml
services:
  web:
    project: ./src/web
    language: js
    host: containerapp
    hooks:
         predeploy:
          posix:
            shell: sh
            run: 'echo aaaa && sleep 50'    
```

runing `azd deploy web` starts building dockerfile immediately, ignoring the hook.

Note:  prepackage hook is also ignored.
