### ISSUE TITLE
[Issue] azd should fail if docker settings are incorrect

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#3551]
I'm using custom docker settings in azure.yaml.

I've noticed that if any of those settings aren't correct, then azd will default to use oryx.

For example, if I incorrectly enter the path or context.

Instead, I think azd should fail saying it couldn't find the dockerfile that is specified in the azure.yaml

**Comment by weikanglim** [comment]
I agree that we should look into making an improvement here. 

We did it out of expediency when we made Oryx's container build an implicit feature, meaning that an azure.yaml that looks like:

```yaml
services:
  from-source:
    host: containerapp
    language: python
```

Will invoke Oryx's container buildpack. 

However, if an explicit docker path is specified:

```yaml
services:
  explicit:
    host: containerapp
    language: python
    docker:
      path: ./Dockerfile
```

We should perhaps always honor the Dockerfile location.

The only small, unlikely, but remaining caveat is that the user could still have left out the explicit `docker:path` configuration but expected it to fail when the Dockerfile was moved to a different location.
