### ISSUE TITLE
Support OCI based helm repository installation

### ISSUE THREAD

**Issue by RichardChen820** [Azure/azure-dev#3562]
I got this error when I was using the helm to install my component to AKS. Seems like it does not support to install from a OCI-based helm chart repository. Have plan to support it? Or I just don't write the `azure.yaml` correctly.

```
stderr: Error: looks like "oci://mcr.microsoft.com/azure-app-configuration/helmchart" is not a valid chart repository or cannot be reached: object required
```
OCI-based repository https://helm.sh/docs/topics/registries/

This is the azure.yaml
```
services:
  configprovider:
    host: aks
    k8s:
      namespace: azappconfig-system
      helm:
         repositories:
          - name: appconfig
            url: oci://mcr.microsoft.com/azure-app-configuration/helmchart
         releases:
          - name: appconfig
            chart: kubernetes-provider
            version: 1.2.0
```
