### ISSUE TITLE
[Issue] UnmatchedPrincipalType in .NET Aspire application with azd provision in GitHub action

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-dev#3581]
In a GitHub action I see this error on azd provision:

```
(✓) Done: Resource group: rg-codebreaker-08-dev
  (✓) Done: Log Analytics workspace: law-ssengodjcf2mu
  (✓) Done: Container Registry: acrssengodjcf2mu
  (✓) Done: Key Vault: cbcosmoskvssengodjcf2mu
  (✓) Done: Container Apps Environment: cae-ssengodjcf2mu

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
UnmatchedPrincipalType: The PrincipalId '[31](https://github.com/CodebreakerApp/chapter8/actions/runs/8399923022/job/23006615246#step:8:32)f0a1d[34](https://github.com/CodebreakerApp/chapter8/actions/runs/8399923022/job/23006615246#step:8:35)db54e05a7dc[39](https://github.com/CodebreakerApp/chapter8/actions/runs/8399923022/job/23006615246#step:8:40)70ccf5729a' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.
```

The error message also contains a typo: *PrinciaplType*

This is the .NET Aspire app model used:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

string dataStore = builder.Configuration["DataStore"] ?? "InMemory";

builder.AddAzureProvisioning();

var cosmos = builder.AddAzureCosmosDB("cbcosmos")
    .AddDatabase("codebreaker");

var gameAPIs = builder.AddProject<Projects.Codebreaker_GameAPIs>("gameapis")
    .WithReference(cosmos)
    .WithEnvironment("DataStore", dataStore);

builder.AddProject<Projects.CodeBreaker_Bot>("bot")
    .WithReference(gameAPIs);

builder.Build().Run();
```

I did `azd init` and `azd pipeline config` (after creating a .github/workflows folder in the src directory).

This is the GitHub Actions workflow:

```yaml
name: Codebreaker Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

# temporary version for daily build
      - name: Update workloads
        run: dotnet workload update --skip-sign-check --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire --skip-sign-check --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision Infrastructure
        run: azd provision --debug --no-prompt

      - name: Deploy Application
        run: azd deploy --no-prompt
```

See this repo: https://github.com/CodebreakerApp/chapter8/

Versions locally:
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)
aspire 8.0.0-preview.5.24170.4/8.0.100      SDK 8.0.200
