### ISSUE TITLE
[Issue] Unable to deploy a basic Blazor WASM application

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-dev#3603]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

`azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)`

**Describe the bug**

I want to deploy a basic Blazor WASM web application to Azure Static Web Apps. I can deploy this manually or using the SWA CLI as-is. If I use AZD, the `package` step creates the correct `dotnet publish` output in a temporary folder. The `deploy` step then uses the SWA CLI to deploy the application but it excludes the `_framework` folder for Blazor. This causes the Blazor WASM application to not work.

**To Reproduce**

- ~~Use this repo: <https://github.com/seesharprun/sidandrews-swa-app>~~ (Better repro steps below)

1. Run these scripts:

    ```shell
    azd init --template azd-starter-bicep
    dotnet new sln --name AZD.Example --output src
    dotnet new gitignore --output src
    dotnet new blazorwasm --name AZD.Example.Blazor --output src/web
    dotnet sln src/AZD.Example.sln add src/web/AZD.Example.Blazor.csproj

    dotnet watch run --project src/web/AZD.Example.Blazor.csproj
    ```

1. Replace **./azure.yaml** with this content:

    ```yaml
    # yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

    name: azd-starter
    services:
        web:
        project: ./src/web
        language: csharp
        host: staticwebapp
        dist: wwwroot
    ```

1. Add this resource to the **Add resources** section of **./infra/main.bicep**:

    ```bicep
    module web 'core/host/staticwebapp.bicep' = {
      name: 'static-web-app'
      scope: rg
      params: {
        name: '${abbrs.webStaticSites}-${resourceToken}'
        location: location
        tags: union(
          tags,
          {
            'azd-service-name': 'web'
          }
        )
      }
    }
    ```

1. Run `azd up --debug`.

1. Observe that Blazor app is missing any CSS or JS files. Only the HTML file is packaged and sent to Azure Static Web Apps.

**Expected behavior**

I expect all of the content in the `dist` folder to be included in the SWA publish.

**Comment by vhvb1989** [comment]
@seesharprun , I created this PR: https://github.com/seesharprun/sidandrews-swa-app/pull/1 to show how you can change the azd up order to let package+deploy to run after provision.

**Comment by seesharprun** [comment]
I'll try this out immediately. I was working on more detailed repro steps in the interim:

1. Run these scripts:

    ```shell
    azd init --template azd-starter-bicep
    dotnet new sln --name AZD.Example --output src
    dotnet new gitignore --output src
    dotnet new blazorwasm --name AZD.Example.Blazor --output src/web
    dotnet sln src/AZD.Example.sln add src/web/AZD.Example.Blazor.csproj

    dotnet watch run --project src/web/AZD.Example.Blazor.csproj
    ```

1. Replace **./azure.yaml** with this content:

    ```yaml
    # yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

    name: azd-starter
    services:
        web:
        project: ./src/web
        language: csharp
        host: staticwebapp
        dist: wwwroot
    ```

1. Add this resource to the **Add resources** section of **./infra/main.bicep**:

    ```bicep
    module web 'core/host/staticwebapp.bicep' = {
      name: 'static-web-app'
      scope: rg
      params: {
        name: '${abbrs.webStaticSites}-${resourceToken}'
        location: location
        tags: union(
          tags,
          {
            'azd-service-name': 'web'
          }
        )
      }
    }
    ```

1. Run `azd up --debug`.

At the end of the day, it illustrated the same issue where the Blazor app deploys successfully but the `_framework` folder is excluded. I will try your fix with both my sample repository and the repro steps.

Thanks!

**Comment by seesharprun** [comment]
Here's some more useful diagnostics.

The temporary folder from the package process (`az package --debug`) contains all of the files to run the Blazor WASM application:

![image](https://github.com/Azure/azure-dev/assets/5067401/081b7345-6f3d-4205-8936-8438cdd14c52)

The zip file created by the deployment process (`az deploy --debug`) doesn't contain the Blazor CSS files and `_framework` folder as illustrated in this screenshot:

![image](https://github.com/Azure/azure-dev/assets/5067401/8d0fb4da-2b9f-4146-9443-0d39ce5ae132)

Something between the `dotnet publish` in the **package** step and the `swa deploy` in the **deploy** step is dropping required files for Blazor WASM. I could get away with not having the CSS files, but dropping the `_framework` folder and the Blazor JS and WASM content means the deployed web application never works or loads.

**Comment by seesharprun** [comment]
I rewrote the repro steps above to make it much easier for others to repro the bug without having to look at my GitHub repository.

I'm also experimenting with your fix and a potential custom `up` workflow that manually calls `dotnet publish` and `swa deploy` with the correct assets.

**Comment by seesharprun** [comment]
For others following along, the fix is to update the `azure.yaml` from the repro steps to this:

```yml
name: azd-starter
services:
  web:
    project: ./src/web
    language: csharp
    host: staticwebapp
    dist: wwwroot
    hooks:
      predeploy:
        posix:
          shell: sh
          run: dotnet publish -c Release --output .
        windows:
          shell: pwsh
          run: dotnet publish -c Release --output .
```
