### ISSUE TITLE
[Issue] Helm deployment namespace conflict

### ISSUE THREAD

**Issue by pauldotyu** [Azure/azure-dev#3673]
- [ x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
```
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)
```

**Describe the bug**
Helm deployments seems to install apps in the namespace that is set via the `azure.yaml` file. If a namespace is not set in the `azure.yaml` file, then it seems that the namespace is defaulted to the name of the helm repository that is configured in the `azure.yaml` file. This can result in a conflict when the namespaces in the `azure.yaml` file and the Helm Chart's `values.yaml` do not match. 

**To Reproduce**
Create a new azd project and set the k8s namespace:
```
services:
  demo:
    host: aks
    k8s:
      namespace: dev # <-- this takes precedence over any namespace setting in helm chart
      service:
        name: store-admin
      helm:
        repositories:
          - name: aks-store-demo # <-- if namespace is not set above, it seems this is the namespace that the app is deployed to
            url: https://pauldotyu.github.io/aks-store-demo
        releases:
          - name: demo
            chart: aks-store-demo/aks-store-demo-chart
            version: 1.0.0
            values: custom-values.yaml # This file is created by the predeploy hook
```

Deploy a helm chart which attempts to set the namespace to something different than what's defined in the azd config.
 
You will see that the app was deployed into `dog` namespace even though the helm chart was configured to deploy to a different namespace.

**Expected behavior** 
If no namespace is defined in the `azure.yaml` file, then the deployment should deploy into the namespace specified in the Helm chart, and if no namespace is defined in the helm chart, then the app should get deployed into the default namespace.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
