### ISSUE TITLE
[remote env] error for short template name

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3713]
error:

![image](https://github.com/Azure/azure-dev/assets/24213737/0e8bbafe-2ece-41f0-80da-ce9d0e5eb123)

azure.yaml

```
name: ii
services:  
  app:
    language: dotnet
    project: ./ii.AppHost/ii.AppHost.csproj
    host: containerapp
state:
  remote:
    backend: AzureBlobStorage
    config:
      accountName: testtenatstoragestate2
```
