### ISSUE TITLE
Incorrect synthesizing of parameters in Bicep environment variables

### ISSUE THREAD

**Issue by miceiken** [Azure/azure-dev#3738]
```
azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)
```
```
➜  ContainerParameterReference dotnet workload --info
 Workload version: 8.0.200-manifests.c4df6daf
 [aspire]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.0-preview.5.24201.12/8.0.100
```

Given this code
```csharp
var builder = DistributedApplication.CreateBuilder(args);

var param = builder.AddParameter("param");
var secretParam = builder.AddParameter("secretParam", true);

builder.AddContainer("dummy", "docker")
    .WithEnvironment("PARAM", param)
    .WithEnvironment("SECRET", secretParam);

builder.Build().Run();
```

The following bicep is synthesized:
```bicep
param param string
@secure()
param secretParam string

[...]

resource dummy 'Microsoft.App/containerApps@2023-05-02-preview' = {
  name: 'dummy'
  location: location
  properties: {
    environmentId: containerAppEnvironment.id
    configuration: {
      activeRevisionsMode: 'Single'
      secrets: [
        {
          name: 'secret'
          value: secretParam
        }
      ]
    }
    template: {
      containers: [
        {
          image: 'docker:latest'
          name: 'dummy'
          env: [
            {
              name: 'PARAM'
              value: 'param'
            }
            {
              name: 'SECRET'
              secretRef: 'secret'
            }
          ]
        }
      ]
      scale: {
        minReplicas: 1
      }
    }
  }
  tags: union(tags, {'aspire-resource-name': 'dummy'})
}
```

Notice how the PARAM env variable gets a string value of 'param', instead of referencing the actual param:
```diff
{
  name: 'PARAM'
-  value: 'param'
+  value: param
}
```

Sorry for using the "param" name as it is a keyword, but it happens for all parameters (that are not secrets), no matter the name.

**Comment by vhvb1989** [comment]
Same as: https://github.com/Azure/azure-dev/issues/3732

We are not supporting env expressions for container.v0, resulting in wrong bicep-generation for the environment.

For the fix, we will be moving container.v0 out of the bicep resources. Azd will create a yaml definition for the container.v0 as it does for project.v0 and dockerfile.v0.
container.v0 won't be created until running `deploy`

@ellismg FYI

**Comment by ellismg** [comment]
This will be fixed by #3820.  We now generate a `.tmpl.yaml` file that looks like this:

```
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: secret
        value: '{{ securedParameter "secretParam" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: dummy
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: PARAM
            value: '{{ parameter "param" }}'
          - name: SECRET
            secretRef: secret
    scale:
      minReplicas: 1
tags:
  azd-service-name: dummy
  aspire-resource-name: dummy
```

Which does the references correctly.
