### ISSUE TITLE
portability issue for generated template in Aspire (.Net in general)

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3825]
When running `azd init` and auto-detecting the dotnet project in *windows*, azd is saving the path to the appHost project using windows path notation:

```
services:  
  app:
    language: dotnet
    project: .\src\AspireWithPostgres.AppHost\AspireWithPostgres.AppHost.csproj
    host: containerapp
```

This becomes an issue when cloning the project in linux/mac, as the path is not found.

The workaround is either deleting azure.yaml and running `azd init` to auto-gen again, or manually updating the path to

```
services:  
  app:
    language: dotnet
    project: ./src/AspireWithPostgres.AppHost/AspireWithPostgres.AppHost.csproj
    host: containerapp
```
