### ISSUE TITLE
[Issue] [aspire] `azd infra synth` ignored by `azd deploy` in azdo ci/cd pipeline

### ISSUE THREAD

**Issue by Bpflugrad** [Azure/azure-dev#3891]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`azd version 1.9.0 (commit 651394c3ddcfadff194d177f8b0ddf06fe3752bf)`

**Describe the bug**
`azd infra synth` has been executed, and the generated templates in the AppHost project are committed and pushed to the build branch, but `azd deploy` generates the `infra` itself, ignoring any manual changes.

**To Reproduce**
- Create a new Aspire Starter App.
- Run `azd init`
- Add `state: remote: backend` for remote configuration.
- Add .azdo/pipelines/azure-dev.yaml
- Run `azd pipeline config`
- Permission created `azconnection` service principal with `Storage Blob Contributor` on your remote configuration blob storage.
- Update project to use `AddConnectionString` in `AppHost`.
- Use `AddReference` on the `ApiService` resource.
- Add `Aspire.Azure.Storage.Blobs` to `ApiService`.
- Run `azd env set AZURE_BLOB_STORAGE_CONNECTION ""` to add string to env.
- Run `azd infra synth`
- Edit `apiservice.tmpl.yaml` to replace `'{{ securedParameter "BlobStorageConnection" }}'` with `{{ .Env.AZURE_BLOB_STORAGE_CONNECTION }}`
- Edit `main.bicep` to add output AZURE_BLOB_STORAGE_CONNECTION string = BlobStorageConnection
- Push to trigger build.

Build will fail at `azd deploy` with message:
`ERROR: failed deploying service 'apiservice': failing invoking action 'deploy', failed executing template file: template: containerApp.tmpl.yaml:21:19: executing "containerApp.tmpl.yaml" at <securedParameter "BlobStorageConnection">: error calling securedParameter: parameter BlobStorageConnection not found`

This indicates that `securedParameter "BlobStorageConnection"` is still in the template.  Note that `containerApp.tmpl.yaml` is the file name, which was the file name from `azd 1.8.2`.

Log message indicates that new template was generated, not the one created by `azd infra synth`:
`2024/05/09 23:45:47 service_target_dotnet_containerapp.go:195: generating container app manifest from /home/vsts/work/1/s/.\AspireInfraExample.AppHost\AspireInfraExample.AppHost.csproj for project apiservice`

**Expected behavior**
Infra created by `azd infra synth` should be used.

**Environment**
Information on your environment:
    - dotnet 8.0.300-preview.24203.14
    - Version 17.10.0 Preview 7.0
    - azd version 1.9.0 (commit 651394c3ddcfadff194d177f8b0ddf06fe3752bf)

**Additional context**
Complete `azure.yaml`:
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: AspireInfraExample
services:  
  app:
    language: dotnet
    project: .\AspireInfraExample.AppHost\AspireInfraExample.AppHost.csproj
    host: containerapp
state:
  remote:
    backend: AzureBlobStorage
    config:
      accountName: azdconfiguration
      containerName: aspireinfraexample
```

Complete `azure-dev.yaml`:
```
trigger:
- master
- staging

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: Install Aspire Workload with Preview
    inputs:
      command: custom
      custom: 'workload'
      arguments: 'install aspire --include-previews --source https://api.nuget.org/v3/index.json'

  - task: setup-azd@0 
    displayName: Install azd

  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.

  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)

  - task: AzureCLI@2
    displayName: Deploy Application
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt --debug
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
```
