### ISSUE TITLE
Add manual" flag

### ISSUE THREAD

**Issue by john0isaac** [Azure/azure-dev#3981]

**Comment by ellismg** [comment]
> to allow for further customizations but it would be good start if we only had a `workflow_dispatch` flag

If these hooks are not tied to the service lifecycle, is the value here that `azd hook run` just runs a shell script with the values from the `.env` file injected into the process environment?

I'm wondering, if instead of forcing folks to write stuff in `azure.yaml` under a `workflow_dispatch` thing is what we want, or if there should be something like `azd env run` or something that runs a command or script with the `.env` files injected?  That would also allow you to do something like `azd env run bash` to get a shell with all the values configured.

**Comment by john0isaac** [comment]
workflow_dispatch is just an example of what I meant but I didn't mean it in the way you understood it, this example will simplify this.

## Old hooks

```yaml
name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
hooks:
  postprovision:
    windows: # Run referenced script that uses environment variables (script shown below)
      shell: pwsh
      run: ./scripts/prepdocs.ps1
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./scripts/prepdocs.sh
      interactive: true
      continueOnError: false
  postdeploy: # Pull environment variable inline from local device and set in .env file
      shell: sh
      run: azd env set REACT_APP_WEB_BASE_URL ${SERVICE_WEB_ENDPOINT_URL}
     
```

## New hooks

```yaml
name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
hooks:
  postprovision:
    windows: # Run referenced script that uses environment variables (script shown below)
      shell: pwsh
      run: ./scripts/prepdocs.ps1
      interactive: true
      continueOnError: false
      manual: true       # NEW
    posix:
      shell: sh
      run: ./scripts/prepdocs.sh
      interactive: true
      continueOnError: false
      manual: true      #NEW
  postdeploy: # Pull environment variable inline from local device and set in .env file
      shell: sh
      run: azd env set REACT_APP_WEB_BASE_URL ${SERVICE_WEB_ENDPOINT_URL}
     
```


Just a flag to stop the hook from automatically running.
It should get it's env vars from azd env.

What you're suggesting is a great feature it maybe a great addition to azd in the future the env vars always bugs me.
But my request is very simple, just allow me to run the hook manually using azd environment.

For example, a hook that adds data to a database may only run once if you run it multiple times it will error.
So if I do `azd up` with the current implementation it will error as it might be in the `postprovision` stage.
