### ISSUE TITLE
Azd should use specified target port from manifest if specified

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#4005]
AppHost

```C#
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.WebApplication1>("api", launchProfileName: null)
       .WithHttpEndpoint(targetPort: 8001)
       .WithEnvironment("HTTP_PORTS", "8001");

builder.Build().Run();
```

Manifest

```JSON
{
  "$schema": "https://json.schemastore.org/aspire-8.0.json",
  "resources": {
    "api": {
      "type": "project.v0",
      "path": "../WebApplication1/WebApplication1.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY": "in_memory",
        "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true",
        "HTTP_PORTS": "8001"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 8001
        }
      }
    }
  }
}
```

YAML

```yaml
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8001 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: api
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: "8001"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
    scale:
      minReplicas: 1
tags:
  azd-service-name: api
  aspire-resource-name: api
```

This results in a deployment that has this as ingress rules when in ACA:

```JSON
{
    "ingress": {
    "fqdn": "<redacted>.azurecontainerapps.io",
    "external": false,
    "targetPort": 8080,
    "exposedPort": 0,
    "transport": "Http",
    "traffic": [
        {
            "weight": 100,
            "latestRevision": true
        }
    ],
    "customDomains": null,
    "allowInsecure": true,
    "ipSecurityRestrictions": null,
    "corsPolicy": null,
    "clientCertificateMode": null,
    "stickySessions": null,
    "additionalPortMappings": null,
    "targetPortHttpScheme": null
    }
}
```

We should be using the specified target port, not 8080.
