### ISSUE TITLE
[Issue] Docker buildargs does not support interpolation

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-dev#4062]
- [ X ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Describe the bug**
If you have a Static App (like React) and a backend api in ACA, it would be nice if we could take the output of the infra deployment (the url) and pass it as `buildArgs` in the dockerfile:

For example: 

```biceps
# main.biceps
...
output REACT_APP_BACKEND_URL string = backend.outputs.uri
```

```yaml
# azure.yaml - Notice the environment variables!
...
    frontend:
        project: "src/frontend"
        host: containerapp
        language: ts
        dist: build
        docker:
            path: Dockerfile
            buildArgs:
                - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
```

```powershell
# deploy infra and populate outputs as environment variables
azd provision --environment dev
# utilize environment variables to interpolate the azure.yaml
azd deploy 
```
