### ISSUE TITLE
Feature request: azd pipeline config --provider azdo -> to re-use existing service connection

### ISSUE THREAD

**Issue by tvriesde** [Azure/azure-dev#4138]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)
azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)

**Output from `azd version`**
azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)

**Describe the bug**
azd pipeline config --provider azdo

azd pipeline config --provider azdo creates service connection and federated identity. many users are not allowed to create service connections, and have to re-use service connections provided by a central platform team.

allow for service connection name to be provided something similar to:
azd pipeline config --provider azdo --use-existing-service-connection true

**Comment by Menghua1** [comment]
@tvriesde Based on the latest version of AZD, if you need to reuse an existing service connection, you can follow these steps:

1. Specify the service connection in your pipeline YAML:
In  `.azdo/pipelines/azure-dev.yml` file, set the `azureSubscription` property to the name of the service connection you want to use. 
```
- task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: <existing service connection name>
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
```

2. Run `azd pipeline config --provider azdo`:
When prompted to select how to authenticate the pipeline to Azure, choose `Skip authentication setup (for manually configured pipelines or existing setup)`.
<img width="939" height="159" alt="Image" src="https://github.com/user-attachments/assets/6bf68db0-aabc-48a0-9962-9f24b3502e5a" />

By following these steps, azd will skip the automated authentication and service connection creation process, and your pipeline will use the manually specified service connection.

If you have any further questions or need additional clarification, please feel free to leave a comment.

CC: @rajeshkamal5050
