### ISSUE TITLE
engsys: idempotent publishing for re-runs

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#4361]
Is there a general strategy we can make artifact publishing idempotent to job re-runs?

Example:

In [publish-cli.yml](https://github.com/Azure/azure-dev/blob/bdcadc9b19c7ef605819ce4bf656cc4c13b36e9d/eng/pipelines/templates/steps/publish-cli.yml#L160) (and anywhere else), when we have a pipeline artifact being published:

```
  - task: 1ES.PublishPipelineArtifact@1
    inputs: 
      targetPath: release
      artifact: UploadedReleaseArtifacts
```

And in a subsequent step such as [create-pull-request](https://github.com/Azure/azure-dev/blob/bdcadc9b19c7ef605819ce4bf656cc4c13b36e9d/eng/pipelines/templates/steps/publish-cli.yml#L225), fails due to a flaky issue. On a rerun, we will get an error:

> ##[error]Artifact UploadedReleaseArtifacts already exists for build 4153919.

Here's a recent [build run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4153919&view=logs&j=ee5de2cd-9e90-5d17-a5a1-f42a8def586d&s=62dbc4f1-f27c-5ddb-f6ac-c39a8a0ad4eb&t=7bcde4f4-ffae-5a2d-8209-b557d47f490a&l=32) demonstrating this issue.
