### ISSUE TITLE
[Issue] `azd hooks run` not respecting `interactive` configuration

### ISSUE THREAD

**Issue by cedricvidal** [Azure/azure-dev#4382]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```
azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
```

**Describe the bug**
azd hooks don't get TTY in interactive mode on `linux`/`sh` and `linux`/`pwsh`

Github repo with code to reproduce
https://github.com/cedricvidal/azd-hook-interactive-python

> This limits the possibility to provide a nice interactive onboarding experience on hosts other than Windows.

**To Reproduce**

On a MacOS or Windows machine
- Clone https://github.com/cedricvidal/azd-hook-interactive-python
- Reopen in Dev Container (Linux `mcr.microsoft.com/devcontainers/python:1-3.12-bullseye`)
- `azd hooks run test-sh` fails
- `azd hooks run test-py` fails
- `azd hooks run test-ps` fails silently

On a Windows machine
- Clone https://github.com/cedricvidal/azd-hook-interactive-python
- `azd hooks run test-sh` fails
- `azd hooks run test-py` fails
- `azd hooks run test-ps` succesfully asks user for "? Input" and prints the value

**Expected behavior**
On Windows and MacOS, within a Linux Dev Container or on the host
- `azd hooks run test-sh` succesfully asks user for "? Input" and prints the value
- `azd hooks run test-py` succesfully asks user for "? Input" and prints the value
- `azd hooks run test-ps` succesfully asks user for "? Input" and prints the value

**Environment**

VS Code: Version: 1.93.1 Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)

**Comment by weikanglim** [comment]
Hi @cedricvidal our team will take a look at this soon. In the meantime, I tried accessing  https://github.com/cedricvidal/azd-hook-interactive-python and got a 404. I think this usually means I may not have the right permissions to view it -- if this repro repository is okay to share, would you be able to check on your side that it's set to public access? Thanks!

**Comment by cedricvidal** [comment]
Hello Wei,

thanks for your quick response! My bad, the repo was private, I changed its visibility to public, you should be able to access it.

Let me know if you have any question.

Cedric

**Comment by weikanglim** [comment]
Hi @cedricvidal, thanks for updating the repro repository. I took a closer look, and it seems that `azd hooks run` isn't respecting the `interactive` flag. However, it does seem to work during the actual hook execution.

I modified the repro slightly to have a valid `preprovision` hook:

```yaml
name: azd-test
hooks:
  preprovision:
    shell: sh
    run: ./test.sh
    interactive: true
    continueOnError: false
```

And verified `azd provision` does indeed prompt:

![image](https://github.com/user-attachments/assets/10e7ae0e-91dc-4d3d-a110-886c5e13476d)

However, just as you have noticed, `azd hooks run preprovision` fails:

![image](https://github.com/user-attachments/assets/c60eedd3-6e49-471d-b2d3-e4dedf9ab1ca)

I have updated the bug based on these findings. cc: @wbreza

**Comment by JeffreyCA** [comment]
I ran into this as well on scripts with `echo`/`Write-Host` - the printed content is visible while the hook is running via `azd hooks run`, but disappears after it completes:

```yaml
hooks:
  predeploy: 
    posix:
      shell: sh
      run: |
        echo "Preparing for multi-region deployment..." 
        sleep 3
      interactive: true
    windows:
      shell: pwsh
      run: |
        Write-Host "Preparing for multi-region deployment..."
        Start-Sleep -Seconds 3
      interactive: true
```

![Image](https://github.com/user-attachments/assets/a745bd89-2e48-4738-8a4b-d6e61d52310c)

![Image](https://github.com/user-attachments/assets/18db9ca3-0d3f-4d7e-9218-117a5c384d46)
