### ISSUE TITLE
[Issue] .NET Aspire - Bind Mount upload operation fails

### ISSUE THREAD

**Issue by tommasodotNET** [Azure/azure-dev#4413]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)

**Describe the bug**
I have the following aspire container resource, using a BindMount:
```csharp
var dab = builder.AddContainer("dab", "mcr.microsoft.com/azure-databases/data-api-builder", "latest") 
    .WithHttpEndpoint(targetPort: 5000, name: "http")    
    .WithOtlpExporter()    
    .WithBindMount("./<PATH_TO_FILE>/dab-config.json", target: "/App/dab-config.json")
```

This is what running azd infra synth with the `azd operations feature on` will generate on Windows:
```yaml
operations:
- type: FileShareUpload  
  description: Upload files for containerapp  
  config:    
    storageAccount: ${AZURE_VOLUMES_STORAGE_ACCOUNT}   
    fileShareName: ${SERVICE_CONTAINERAPP_FILE_SHARE_BM0_NAME}    
    path: C:\Users\tstocchi\AppData\Local\Temp\azd-provision3110193039\D:\src\<PATH_TO_FILE>\dab-config.json
```

Running the same command on WSL will generate this:
```yaml
operations:
- type: FileShareUpload
  description: Upload files for dab
  config:
    storageAccount: ${AZURE_VOLUMES_STORAGE_ACCOUNT}
    fileShareName: ${SERVICE_DAB_FILE_SHARE_BM0_NAME}
    path: /mnt/d/src/<PATH_TO_FILE>/dab-config.json
```

On Windows, `azd up` will fail because the path for the file to be uploaded cannot be found. I think this might be cause by the fact that the path is formed as <TEMP_FOLDER>/<PATH_TO_FILE>/dab-config.json.

On WSL, `azd up` will fail because it uses the PUT verb, which is not supported:
```
ERROR: error executing step command 'provision': deployment failed: error running bind mount operation: error binding mount: error uplaoding file to file share: PUT https://<STORAGE_ACCOUNT_ENDPOINT>.file.core.windows.net/dab-bm0/
_____________________________________
RESPONSE 405: 405 The resource doesn't support specified Http Verb.
ERROR CODE: UnsupportedHttpVerb
```

**To Reproduce**
- add the above code to a .NET Aspire project
- activate the azd operations feature 
- run azd up (and azd infra synth to see the generated operations file)

**Expected behavior**
I expect the azd provision step to be able to upload the file referenced in the BindMount.

**Environment**
Information on your environment:
    * .NET Aspire 8.2.0
    * IDE and version : VS Code
    * OS: Windows and WSL (Ubuntu 22.04.4 LTS)
