### ISSUE TITLE
[Issue] Service skipped during `azd deploy` and not sure why

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#4605]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:

1.11

**Describe the bug**

One of my services is being skipped, but I'm not sure why.

![Image](https://github.com/user-attachments/assets/a24be6d7-5a2a-45ce-b3a5-d369c4ea222c)

**To Reproduce**

Run `azd deploy` with this

 
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: src
metadata:
  template: azd-init@1.11.0
services:
  api:
    project: api
    host: containerapp
    language: dotnet
    docker:
      path: Dockerfile

  web:
    project: web
    host: containerapp
    language: ts
    dist: dist
    docker:
      path: Dockerfile
      buildArgs:
        - "VITE_API_URI"

```

**Expected behavior**

I expect it to deploy both. And if it skips one, it should tell me why.

**Notes**

If I manually run `azd deploy api`, it will deploy. but it doesn't work if I just run `azd deploy`.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
