### ISSUE TITLE
[Issue] Failed to deploy app when app name too long or different app name has same long prefix

### ISSUE THREAD

**Issue by rujche** [Azure/azure-dev#4653]
Link to sample project: https://github.com/microsoft/SJAD

## Reproduce step:
1. Run `azd init`, then manually change the app name in `azure.yaml`. (It can be achieved by another way: Rename the folder name then run `azd init`)
3. Run `azd up`

### 1.1. Example `azure.yaml`:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/azure-javaee/azure-dev/feature/sjad/schemas/alpha/azure.yaml.json

name: sjad
metadata:
    template: azd-init@0.0.0-dev.0
services:
    long-long-long-long-long-long-long-long-long-common-prefix-api:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: api
        host: containerapp
        language: java
        docker:
            path: Dockerfile
    long-long-long-long-long-long-long-long-long-common-prefix-email-service:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: email-service
        host: containerapp
        language: java
        docker:
            path: Dockerfile
    long-long-long-long-long-long-long-long-long-common-prefix-web:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: web
        host: containerapp
        language: java
        docker:
            path: Dockerfile
hooks:
    prepackage:
        windows:
            shell: pwsh
            run: .\mvnw.cmd clean package -DskipTests
        posix:
            shell: sh
            run: ./mvnw clean package -DskipTests
resources:
    long-long-long-long-long-long-long-long-long-common-prefix-api:
        type: host.containerapp
        uses:
            - mongo
            - servicebus
        port: 3100
    long-long-long-long-long-long-long-long-long-common-prefix-email-service:
        type: host.containerapp
        uses:
            - servicebus
        port: 8081
    long-long-long-long-long-long-long-long-long-common-prefix-web:
        type: host.containerapp
        uses:
            - long-long-long-long-long-long-long-long-long-common-prefix-api
            - long-long-long-long-long-long-long-long-long-common-prefix-email-service
        port: 8080
    mongo:
        type: db.mongo
        databaseName: todo
    servicebus:
        type: messaging.servicebus
        authType: userAssignedManagedIdentity
        isJms: true
```

### 1.2. Error message:
```shell
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidDeployment: The provided deployment name 'longLongLongLongLongLongLongLongLongCommonPrefixEmailServiceidentity' has a length of '68' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.
InvalidDeployment: The provided deployment name 'longLongLongLongLongLongLongLongLongCommonPrefixEmailService-fetch-image' has a length of '72' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.

TraceID: aa4f08e646a8222935cdbdbb2dc9bab8
```

### 2.1. Example `azure.yaml`:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/azure-javaee/azure-dev/feature/sjad/schemas/alpha/azure.yaml.json

name: sjad
metadata:
    template: azd-init@0.0.0-dev.0
services:
    long-long-long-long-long-long--common-prefix-api:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: api
        host: containerapp
        language: java
        docker:
            path: Dockerfile
    long-long-long-long-long-long-common-prefix-email-service:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: email-service
        host: containerapp
        language: java
        docker:
            path: Dockerfile
    long-long-long-long-long-long-common-prefix-web:
        parentPath: C:\Users\rujche\Work\git-workspace\main\SJAD
        project: web
        host: containerapp
        language: java
        docker:
            path: Dockerfile
hooks:
    prepackage:
        windows:
            shell: pwsh
            run: .\mvnw.cmd clean package -DskipTests
        posix:
            shell: sh
            run: ./mvnw clean package -DskipTests
resources:
    long-long-long-long-long-long--common-prefix-api:
        type: host.containerapp
        uses:
            - mongo
            - servicebus
        port: 3100
    long-long-long-long-long-long-common-prefix-email-service:
        type: host.containerapp
        uses:
            - servicebus
        port: 8081
    long-long-long-long-long-long-common-prefix-web:
        type: host.containerapp
        uses:
            - long-long-long-long-long-long--common-prefix-api
            - long-long-long-long-long-long-common-prefix-email-service
        port: 8080
    mongo:
        type: db.mongo
        databaseName: todo
    servicebus:
        type: messaging.servicebus
        authType: userAssignedManagedIdentity
        isJms: true
```
### 2.2.  Error message:
```shell
Creating/Updating resources
  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F50328023-df85-46b6-96f5-c4566d7b063c%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Frujche-azd-env-241226-03-1735195829

  (✓) Done: Resource group: rg-rujche-azd-env-241226-03 (5.657s)
  (✓) Done: Log Analytics workspace: log-wlnou27362ogq (20.044s)
  (✓) Done: Application Insights: appi-wlnou27362ogq (4.693s)
  (✓) Done: Container Registry: crwlnou27362ogq (24.405s)
  (✓) Done: Key Vault: kv-wlnou27362ogq (22.937s)
  (✓) Done: Portal dashboard: dash-wlnou27362ogq (2.728s)
  (✓) Done: Service Bus Namespace: sb-wlnou27362ogq (1m9.293s)
  (✓) Done: Container Apps Environment: cae-wlnou27362ogq (38.582s)
  (✓) Done: Container App: long-long-long-long-long-long (23.234s)
  (✓) Done: Azure Cosmos DB: cosmos-wlnou27362ogq (2m12.844s)

Deploying services (azd deploy)

Deploying service long-long-long-long-long-long--common-prefix-api
  (x) Failed: Deploying service long-long-long-long-long-long--common-prefix-api

ERROR: error executing step command 'deploy --all': getting target resource: resource not found: unable to find a resource tagged with 'azd-service-name: long-long-long-long-long-long--common-prefix-api'. Ensure the service resource is correctly tagged in your infrastructure configuration, and rerun provision

Process finished with the exit code 1
```

### 2.3. The deployment details page shows it completed:
> ![Image](https://github.com/user-attachments/assets/0b3e8277-785b-4626-96d2-eade49891e7d)

### 2.4. In portal, expected 3 Container App, but only one Container App created: 
> ![Image](https://github.com/user-attachments/assets/0c2d2934-4f64-4896-888c-9295580bc036)

### 2.5. Actual tab in the Container App
> ![Image](https://github.com/user-attachments/assets/6f2b07eb-a895-4a12-bba2-6b29caacc4a8)
