### ISSUE TITLE
compose: `azd add` support for Key Vaults

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#4682]
------------
Edge cases:

- Empty -> add MongoDB or Redis
  -  Preview provision should show KV
- KV exists -> add MongoDB or Redis
  -  Preview provision should not show KV?
- Empty -> add Postgres or other

**Comment by weikanglim** [comment]
Some design options that I'm still thinking through:

## Secrets - leveraging azd environment keyvault

Once thing I'm thinking about is that with #4517, perhaps we wouldn't need to introduce an intermediate KeyVault support at the `azure.yaml` application workload model. 

Instead, we have a managed secrets experience where users can do:

```yaml
resources:
  api:
    type: host.containerapp
    env:
    - OPENAPI_KEY: ${secrets.OPENAPI_KEY}
 ```

This references the secret stored in azd's environment key vault and eliminates the need for an explicitly defined KeyVault managed in IaC. 

Another good idea we can build from is that KeyVault secrets have tag/label properties. One thing we could even do is have tags an autoconfiguration applied -- if a secret has `label: api` applied for example, perhaps it just flows into the secret configuration (we'd have to think through what this means).

## Secrets - with an explicit KeyVault

The other design I could think of is to be explicit in the KeyVault declaration. In this flow, we'd also have to think about when the secrets prompting happens and the effects of such a thing.

```yml
services:
  vault:
    type: vault
    secrets:
    - openApiKey
  app:
    type: host.containerapp
    env:
    - name: OPENAPI_KEY
      secretValue: ${vault.openApiKey}
```

This design would lend itself to multiple keyvaults being possible for extra layering options.
