### ISSUE TITLE
[env with secrets] Support for pipeline config

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#4699]
When mapping an ENV key to a secret for the pipeline configuration in azure.yaml like:

```yaml
pipeline:
  secrets:
    - ENV-FOO 
  variables:
    - ENV-FOO
```

azd should check if the value of the env is an Azure Key Vault secret and if yes, pull the value and save it as secret for the pipeline.

But, if the env key is defined as a variable, azd should grant read-access to the key-vault account for the service-principal used for the pipeline.
