### ISSUE TITLE
[Issue] Symlinks ignored when zipping for app service deployment

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-dev#4715]
- [/] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 1.11.1 (commit ae08ceba17c7078c547df9ee5f97e9e7ceb2fe53)`

**Describe the bug**
We have the following `azure.yaml`:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ai-document-review
metadata:
  template: ai-document-review@1.0.0
infra:
  provider: terraform
services:
  app:
    project: app/api
    host: appservice
    language: python
    hooks:
      # Build the UI code into the API's www directory.
      prepackage:
        shell: sh
        run: 'task app-build-ui'
  flows:
    project: flows
    host: appservice
    language: python
```

The `app` service is a FastAPI Python application, and it consumes a set of common utils in our monorepo from the top-level directory (in a folder called `common`). To reference these we use a symlink within the `app/api` directory:

<img width="328" alt="Image" src="https://github.com/user-attachments/assets/484af547-df32-40a5-b690-87d9082d3561" />

When trying to deploy the service with `azd up`, we run into the following challenge:

```
ERROR: error executing step command 'package --all': failed packaging service 'app': open /var/folders/kl/dwz9d6xx5jx9s3ygwtqc5q_c0000gn/T/azd2971955672/common: no such file or directory
```

Which I've tracked down to the copy implementation in the cli:

https://github.com/Azure/azure-dev/blob/88ad9bc2cf8e63ef6e0e6b4577770127a162fc3d/cli/azd/pkg/project/project_utils.go#L54 

It seems it uses [this library](https://github.com/otiai10/copy) and doesn't pass any options for:

```go
OnSymlink func(src string) SymlinkAction
```

Which defaults to ignoring them: https://github.com/otiai10/copy/blob/5ef5923d6ff098ea7a51792c1ec963d04fad9794/copy.go#L307

**To Reproduce**
1. Create new Python App Service `azd` template with an appservice service in the `azure.yaml` config
2. Add `common` folder to root and create dummy util
3. Add symlink to common within `src/api` directory
4. Call the util from the api `main.py`
5. `azd up`

**Expected behavior**
Symlinks should be respected and `Deep` copied, or failing that a new option should be introduced to enable this

**Environment**
- Mac M3, Python 3.12.8
