### ISSUE TITLE
Add ability to setup 'condition:' for Service deployment

### ISSUE THREAD

**Issue by crpietschmann** [Azure/azure-dev#4732]
I'm trying to setup an AZD template that deploys a solution with multiple services, including a service that I want to be deployed only if a specific input parameter to the Azure Bicep is set to 'true'. Such as 'DEPLOY_AML_MODEL' = 'true'. I'm using this to conditionally provision Azure Resources in the 'infra' provisioning. In my case it's an Azure Machine Learning service. I'm using an AZD service to deploy the AML Model, and I'd like to have that model deployment conditional based on if the infra has provisioned the AML service or not.

I'd like to add a 'condition' element to the Service, when evaluated to be 'true' will trigger the deployment, when 'false' it wont deploy the service, like this:

```
condition: ${DEPLOY_AML_MODEL}
```

Here's an example of what I'm trying to do when setting up the Azure Machine Learning model deployment within the `azure.yaml`:

```
  AMLReranker:
    condition: ${DEPLOY_AML_MODEL}
    project: ./src/amlreranker
    host: ai.endpoint
    config:
      workspace: ${AZURE_AML_WORKSPACE_NAME}
      model:
        path: ./model/
        code_configuration:
          code: ./scoring/
          scoring_script: score_bgev2m3_aml.py
        environment:
          name: bgev2m3-env 
          build: 
            path: ./environment/
        instance_type: STANDARD_D16AS_V4
        instance_count: 1
        request_settings:
          request_timeout_ms: 120000
    dependsOn:
      - infra
```

It would be really amazing if `azd` could implement this functionality! Thanks!
