### ISSUE TITLE
compose: messaging - event hubs and service bus

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#4742]
This issue tracks enablement of initial set of messaging services: Event Hubs and Service Bus.

# Schema

Managed identity is enabled by default.

## Event Hubs

Definition:
```yaml
resources:
  event-hubs
    type: messaging.eventhubs
    hubs:
    - events
```

Binding environment variables:

- `AZURE_EVENT_HUBS_NAME` - Name of the Event Hubs namespace (Java clients)
- `AZURE_EVENT_HUBS_HOST` - Hostname of the Event Hubs namespace (most other languages)

## Service Bus

```yaml
resources:
  service-bus
    type: messaging.servicebus
    queues:
    - myQueue
    topics:
    - myTopic
```

Binding environment variables:

- `AZURE_SERVICE_BUS_NAME` - Name of the Service Hub namespace (Java clients)
- `AZURE_SERVICE_BUS_HOST` - Hostname of the Service Hub namespace (most other languages)

## UI

`azd add`

https://github.com/user-attachments/assets/d7a8a9fb-9acb-4789-953c-810db68a6178
