### ISSUE TITLE
Feature request: Support multiple infrastructure deployments in AZD provision cmd.

### ISSUE THREAD

**Issue by HadwaAbdelhalem** [Azure/azure-dev#4755]
AZD provision cmd deploys infrastructure resources in a single deployment. For some use cases, the resources can be created in separate multiple deployments for various reasons, like different resource lifecycles, different personas have access/ownership to certain resource type deployments.

Proposal:
update the azd provision cmd to specify deployment.

```
# Folder Structure

- Infra
 ├──network
    - main.tf OR main Bicep
 ├── database
   - main.tf OR main Bicep
 ├── Apps
   - main.tf OR main Bicep

```
# azure.yaml
proposal adds an optional deployment property to the infra section of the azure.yaml schema.
 -  Deployments is list of objects to list [deployment name, relative path to the deployment folder from ./infra , and order for the deployment]. 
 - Deployments property cannot be provided if module property is provided.
 - Deployment property aims to control/support the multi deployment approach, while module property supports the single deployment style.

```yaml
infra:
  provider: terraform
  module: ./infra
  path: ./infra
  deployments: [
    {
      name: "network",
      path: "./network",
      order: 1
    },
    {
      name: "database",
      path: "./database",
      order: 2
    },
    {
      name: "applications",
      path: "./app",
      order: 3
    }
  ]
```
# azd cmds
```cmd
azd provision --deployment <deploymentName> 

Deploy specific group of resources in a single deployment.

azd provision --all

Deploy all resources in all deployments/folders in sequence based on the order field within the deployments array.
```
