### ISSUE TITLE
AZD Remote environment with Terraform local backend

### ISSUE THREAD

**Issue by HadwaAbdelhalem** [Azure/azure-dev#4756]
When AZD is configured to use Remote environment, it stores the environment related files in the storage account. 

Using Terraform as IaC deployment tool, there are env specific additional files withing (.terraform) folder that gets created inside the .azure/ENVNAME folder like state files, and plan files used for the deployment folder. These files need to be stored to the env files in the storage account as well to be able to have the same consistent deployment details and state file available when using different vms as the files now stored globally and not locally on the machine.

Repro step:

- Clone terrasform template like https://github.com/Azure-Samples/todo-nodejs-mongo-terraform.git
- Update azure.yaml to enable azd remote state 
 ``` yaml
name: azd-project-name
state:
  remote:
    backend: AzureBlobStorage
    config:
      accountName: azdremotestate
      containerName: myproject # Defaults to project name if not specified

```
- Run azd up cmd to deploy the app and infrastructure.
- Check the storage account for the environment. the state files are not there
