### ISSUE TITLE
[Issue] Container entrypoints aren't respected in azd with .NET Aspire

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#4786]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.12.0 (commit dc37b930ef8b80340a510c09a6e657ef5bda4f55)

**Describe the bug**
When setting the entrypoint to a container, `azd` is not setting the container command on ACA.

**To Reproduce**

```C#
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache")
    .WithEntrypoint("/bin/sh")
    .WithArgs("-c", "redis-server --protected-mode yes")
    .WithRedisInsight();
```

here is the aspire manifest:

```json
{
  "$schema": "https://json.schemastore.org/aspire-8.0.json",
  "resources": {
    "cache": {
      "type": "container.v0",
      "connectionString": "{cache.bindings.tcp.host}:{cache.bindings.tcp.port}",
      "image": "docker.io/library/redis:7.4",
      "entrypoint": "/bin/sh",
      "args": [
        "-c",
        "redis-server --protected-mode yes"
      ],
      "bindings": {
        "tcp": {
          "scheme": "tcp",
          "protocol": "tcp",
          "transport": "tcp",
          "targetPort": 6379
        }
      }
    },
```

azd infra synth that project and inspect the output

```yaml
api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 6379
      transport: tcp
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: cache
        args:
          - -c
          - redis-server --protected-mode yes
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
    scale:
      minReplicas: 1
tags:
  azd-service-name: cache
  aspire-resource-name: cache
```

The `args` are populated correctly, but the `command` isn't.
**Expected behavior**
The container's command should be set to `/bin/sh`. 

**Additional context**
`entrypoint` was added in .NET Aspire after 8.0-preview1, but before `8.0.0` shipped.

* https://github.com/dotnet/aspire/pull/1341
* https://github.com/dotnet/aspire/blob/release/8.0/src/Schema/aspire-8.0.json#L43-L59
* https://json.schemastore.org/aspire-8.0.json

cc @vhvb1989
