### ISSUE TITLE
Feature: Keep plain text in env value in azure.yaml

### ISSUE THREAD

**Issue by rujche** [Azure/azure-dev#4911]
## Current behavior

For azure.yaml like this:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: spring-cloud-azure-postgresql-sample
metadata:
    template: azd-init@0.0.0-dev.0
services:
    postgresql-sample:
        project: .
        host: containerapp
        language: java
resources:
    rujchedb:
        type: db.postgres
    postgresql-sample:
        type: host.containerapp
        uses:
            - rujchedb
        port: 8080
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:${POSTGRES_URL}
            - name: SPRING_DATASOURCE_USERNAME
              value: ${POSTGRES_USERNAME}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${POSTGRES_PASSWORD}
```

When run `azd infra synth`, it will output bicep files like this:

![Image](https://github.com/user-attachments/assets/8a6d655b-8a90-41b5-bbb8-dee7171ff2c6)

## Expected behavior

But actually, there are 2 gaps between current behavior and my expectation:

1. I expect to keep the prefix (`jdbc:`) in the value.
2. I expect to keep the plain text (like `${POSTGRES_USERNAME}`) instead of creating a bicep parameter.

## Link to related code
https://github.com/Azure/azure-dev/blob/09aeb2c359091e2474834cd38685c82ca6836adf/cli/azd/pkg/project/scaffold_gen.go#L406-L411
