### ISSUE TITLE
[AI Compose] Improve location picker to handle location availability between model versions

### ISSUE THREAD

**Issue by JeffreyCA** [Azure/azure-dev#4919]
I noticed for some models like Phi-4, an older version like `4` may be supported in East US 2, but the latest version `7` may be unsupported:

![Image](https://github.com/user-attachments/assets/e99fa7e7-fee6-4b58-9311-a3e46a175be9)

It doesn't look like the enhanced model location picker handles this scenario. With the following `azure.yaml` config to deploy Phi-4 version 7, `azd provision` still recommend East US 2 as a suitable location, resulting in a deployment failure:

```yml
name: ai-search
resources:
  ai-project:
    type: ai.project
    models:
      - name: Phi-4
        version: "7"
        format: Microsoft
        sku:
          name: GlobalStandard
          usageName: AIServices.GlobalStandard.MaaS
          capacity: 1
```

![Image](https://github.com/user-attachments/assets/f099d6df-4772-4d05-bc9c-ab472301d34a)

![Image](https://github.com/user-attachments/assets/e90e1227-d99e-4c22-ab60-f262f667cd40)
