### ISSUE TITLE
time-to-live flag for `azd up`

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#5011]
This is a customer ask from MVP 2025.

time-to-live allows automatic tear down of Azure resources. Important for ephemeral workload.

**Comment by spboyer** [comment]
After investigation, we believe TTL/auto-delete is better handled at the Azure platform level rather than baked into azd. azd is a deployment tool, not a resource lifecycle manager.

**Existing solutions for ephemeral workloads:**

1. **Tag-based expiry + Azure Policy** — Add an `azd-expires-at` tag via Bicep, then use Azure Policy or a scheduled Azure Function to clean up expired resource groups.

2. **Scheduled `azd down` via GitHub Actions** — Add a post-deploy hook or workflow that dispatches a delayed GitHub Action:
   ```yaml
   # .github/workflows/cleanup.yml
   on:
     schedule:
       - cron: '0 0 * * *'  # daily check
   jobs:
     cleanup:
       runs-on: ubuntu-latest
       steps:
         - run: azd down --force
   ```

3. **Azure Dev/Test Labs** — Has built-in auto-shutdown and expiry policies for ephemeral environments.

Closing as this is better addressed through documentation and existing Azure platform capabilities rather than a CLI flag.

If there's strong demand for a built-in `--ttl` flag, please reopen with specific workflow requirements.
