### ISSUE TITLE
compose: support linking env directly to keyvault secret

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#5015]
Maybe something like:

```yaml
services:
  host:
    env:
    - name: MY_SECRET
       secret: ${<akvs reference?>}
```
