### ISSUE TITLE
compose: static site support

### ISSUE THREAD

**Issue by JeffreyCA** [Azure/azure-dev#5094]
We currently don't have a good story for supporting static sites, including single-page applications (SPA).

One way to support this is through [Azure Static Web Apps](https://azure.microsoft.com/en-us/products/app-service/static), which azd supports (but not in compose).

Some open questions:

## API routing

Azure Static Web Apps can **link** to an API backend like Functions, App Service, Container App, or APIM. Once linked to a backend, any requests to the static web app with a route that starts with `/api` are proxied to the same route on the linked backend app.

![Image](https://github.com/user-attachments/assets/5f82de74-46b1-4073-a42b-373491984fa9)

If we choose not to, then the backend API host information would be needed to package the static site assets.

In our TODO app templates today, this is achieved through hooks:
https://github.com/Azure-Samples/todo-nodejs-mongo/blob/41b6bc2027d8b1e6c50ce044a2e27ff0cab8cbc6/azure.yaml#L23-L36

However with composability, we currently don't emit the backend service host information as Bicep outputs. We may want a cleaner way to achieve this without hooks, like an `env` property to map this information, like:

```yaml
services:
  web:
    project: src/web
    host: staticwebapp
    language: ts
    dist: dist
    env:
      VITE_API_BASE_URL: "$API_BASE_URL"
      VITE_APPLICATIONINSIGHTS_CONNECTION_STRING: "$APPLICATIONINSIGHTS_CONNECTION_STRING"
```

## SPA configuration

When deploying SPAs to Azure Static Web Apps, the web app needs to be configured differently through a configuration file. From [Fallback Routes](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes):

> Single Page Applications often rely on client-side routing. These client-side routing rules update the browser's window location without making requests back to the server. If you refresh the page, or go directly to URLs generated by client-side routing rules, a server-side fallback route is required to serve the appropriate HTML page. The fallback page is often designated as index.html for your client-side app.

**staticwebapp.config.json**
```json
{
  "navigationFallback": {
    "rewrite": "/index.html"
  }
}
```
