### ISSUE TITLE
Add support for OIDC+Terraform in pipeline config

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#5264]
AZD is currently forcing client-secret flow for terraform (as part of the pipeline auto generation).
AZD is also trying to set up a client-secret.
Update AZD to support OIDC for terraform pipelines the same way we do for Bicep.

**Comment by HadwaAbdelhalem** [comment]
AZD does not manage the authentications of the terraform providers. It expects users to auth using AZ CLI and set the needed auth related variables as env variables prior to running azd provision cmd . Those auth variables might vary based on the used terraform provider and the auth approach selected by users. for example, for the same azd template, users can choose to auth using service principal +secret for local developer experience, but opt in using federated credentials auth for executing the workflows.

for AzureRM, and AzureAD providers, users Set (ARM_CLIENT_ID, ...e.g) variables to define the Auth selected option after they run az login, while for powerplatform those variables are (POWERPLATFORM_CLIENT_ID ) and for fabric terraform provider (FABRIC_CLIENT_ID, ...e.g) those Auth variables are named differently.

While deploying resources using any on the above provider is enabled in AZD up/provision experience, the AZD pipeline command currently allows only creating client-credentials when running azd pipeline config on an azd terraform template.

The ask is to modify the [GH_provider ](https://github.com/Azure/azure-dev/blob/28c3cf775d2093ce14e9dc73655227f08408059e/cli/azd/pkg/pipeline/github_provider.go#L361) to unblock the combination for Terraform+federated credentials. 

The **azd pipeline config --auth-type federated** shall add GH repo variables to store (AZURE_CLIENT_ID, AZURE_TENANT_ID, and 
          AZURE_SUBSCRIPTION_ID) based on the created identity by the pipeline config cmd.

below is a sample for a working azd-dev.yaml on an azd terraform template to run using federated credentials. 

```yaml
on:
  push:
    branches:
      - main
     
# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config --auth-type federated`
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Login to Azure (Federated Credentials)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Authenticate with Azure Developer CLI
        run: |
          azd auth login --client-id ${{ vars.AZURE_CLIENT_ID }} --tenant-id ${{ vars.AZURE_TENANT_ID }} --federated-credential-provider "github"

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          RS_ACCOUNT_NAME: ${{ vars.RS_ACCOUNT_NAME }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}


      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
```
