### ISSUE TITLE
Layered Configuration Files

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#5318]
**Summary**: Support environment-specific configuration files that merge with base configuration to enable environment-specific overrides.

**Acceptance Criteria**:

- [ ] Support environment-specific YAML files (e.g., `azure.dev.yaml`)
- [ ] Configuration merging strategy (base + environment-specific)
- [ ] Override capabilities for all configuration sections
- [ ] Validation of merged configurations
- [ ] Clear precedence rules for configuration merging
- [ ] Support for environment-specific secrets and parameters
- [ ] Error handling for configuration conflicts

**Comment by JeffreyCA** [comment]
I was thinking one area we could draw inspiration from is Docker Compose: https://docs.docker.com/reference/compose-file/

### Merging
https://docs.docker.com/reference/compose-file/merge/

For instance, they use an additive approach for certain properties that are lists, so:

```yaml
services:
  foo:
    DNS:
      - 1.1.1.1
```

➕

```yaml
services:
  foo:
    DNS: 
      - 8.8.8.8
```

🟰

```yaml
services:
  foo:
    DNS:
      - 1.1.1.1
      - 8.8.8.8
```

And because of this, they support [special YAML tags `!reset` and `!replace`](https://docs.docker.com/reference/compose-file/merge/#reset-value) to be able to remove and replace values instead of always appending.

### Fragments and Include
These might not apply for us, but they support some more advanced features like [include](https://docs.docker.com/reference/compose-file/include/) and the ability to reuse YAML snippets multiple times in a file using [extensions](https://docs.docker.com/reference/compose-file/extension/) and [YAML anchors/aliases](https://yaml.org/spec/1.2-old/spec.html#id2765878).
