### ISSUE TITLE
[Issue] Recent changes to azd seem to have broken .NET Aspire Azure CI/CD pipeline provision & deploy

### ISSUE THREAD

**Issue by joseph-hungerman** [Azure/azure-dev#5390]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: 2.74.0

**Describe the bug**
I was struggling with this last week when I was using the daily version in my Azure DevOps CI/CD pipeline. I reverted to the full release and it went away. Now it is back. I am worried that a recent change broke the Azure deployment for Aspire.

I am using azure cli auth. and just prior to the step I am logged in: 

{
  "auth": {
    "useAzCliAuth": "true"
  }
}
=== azd Auth Status ===
Logged in to Azure

-- Core Error
Analyzing Aspire Application (this might take a moment...)
Downloading Bicep
  (✓) Done: Downloading Bicep
Initialize bicep provider
Retrieving subscriptions...

ERROR: resolving bicep parameters file: fetching current principal type: fetching login details: not logged in, run `azd auth login` to login

**Comment by groovejumper** [comment]
Same happening here - these pipelines worked fine yesterday. In case it's relevant, the azure devops pipeline in an earlier step uses setup-azd@1, which has worked fine.

The provisioning step:
  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)

Results yesterday:
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Analyzing Aspire Application (this might take a moment...)
Downloading Bicep
  (✓) Done: Downloading Bicep
Initialize bicep provider
Retrieving subscriptions...
Reading subscription and location from environment...
Subscription: [subscription]
Location: East US 2

Results today:
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Analyzing Aspire Application (this might take a moment...)
Downloading Bicep
  (✓) Done: Downloading Bicep
Initialize bicep provider
Retrieving subscriptions...

ERROR: initializing provisioning manager: resolving bicep parameters file: fetching current principal type: fetching login details: not logged in, run `azd auth login` to login

##[error]Script failed with exit code: 1

**Comment by groovejumper** [comment]
In case it's relevant, I have not yet upgraded from Aspire 9.2 to 9.3, and my pipelines were created using the "old" strategy with AZD_INITIAL_ENVIRONMENT_CONFIG (which, by the way, I am thankful has gone away, I just haven't had time to upgrade my app and pipelines yet).

Since yesterday's working execution showed "Reading subscription and location from environment..." followed by my subscription details, and today's non-working one showed "Retrieving subscriptions...", maybe it's a clue that the 9.2 hidden config isn't being used i.e. something is not backwards-compatible.

I want to upgrade but on my own time, so if this is the case, is there an easy path to update my pipeline to use whatever component version is breaking to the previous one?

Maybe change this:
  - task: setup-azd@1
    displayName: Install azd
To this:
  - task: setup-azd@1
    inputs:
      version '1.17.0'
    displayName: Install azd

I think 1.17.0 would've been the latest version until yesterday?

**Comment by joseph-hungerman** [comment]
I am on 9.0.3. Everything worked until I started getting the errors late last week when using the daily preview version. I reverted my pipeline to the standard version and it worked. Now it's failing again so I am assuming the problematic code was promoted

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you help triage this one?

**Comment by joseph-hungerman** [comment]
The daily version was failing on Wednesday if the day helps pinpoint the issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mathieumack** [comment]
Hi,

I have the same issue with my pipelines on Azure DevOps.
Don't have Aspire installed, just use azd for provisioning and deployment.

Message: 
```
ERROR: initializing provisioning manager: resolving bicep parameters file: fetching current principal type: fetching login details: not logged in, run `azd auth login` to login`

```

Note about my pipeline, i've configured azd to use az cli authentication :

```
- pwsh: |
    azd config set auth.useAzCliAuth "true"
```

**Comment by mathieumack** [comment]
More informations : 
Everything works with version 1.17.0.
Failed with version 1.17.1

**Comment by vhvb1989** [comment]
There is a regression on 1.17.1
The issue impacts folks delegating auth to `az` (using `azd config set auth.useAzCliAuth "true"`).  

This is why it is observable from ADO pipelines as commented by @mathieumack.

For 1.17.1, AZD can provide the `principalId type` but we did not consider the auth-delegation option for az, causing the issue.

Workaround you can apply immediately while we work on a fix for 1.17.2
- install 1.17.0 as mentioned by @groovejumper  https://github.com/Azure/azure-dev/issues/5390#issuecomment-2994244981

**Comment by faisalriazz** [comment]
@vhvb1989 We are facing the same issue here, everything was working fine last weekend. Now the pipeline is failing with 
```
Analyzing Aspire Application (this might take a moment...)

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Downloading Bicep
  (✓) Done: Downloading Bicep
Initialize bicep provider
Retrieving subscriptions...

ERROR: initializing provisioning manager: resolving bicep parameters file: fetching current principal type: fetching login details: not logged in, run `azd auth login` to login
```
Additionaly, did not find any clear instructions on how to use azd `version 1.17.0 ` in pipline. below is the task to install azd in pipeline
```yml
- task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash
        azd version
       
```
Pipeline was configured using `azd pipeline config --provider azdo`

**Comment by joseph-hungerman** [comment]
Change the bash task to this:
              - task: ***@***.***
                displayName: Install azd
                inputs:
                  version: '1.17.0'




Joseph Hungerman
Founder/CEO
SEE-EYE, Inc.
ph: (615) 559-9495
em: ***@***.***

https://see-eye.io<https://see-eye.io/>

Let's meet! https://savvycal.com/joseph-hungerman
________________________________

**Comment by faisalriazz** [comment]
@joseph-hungerman thanks for your input. Getting error `unexpected property version`
```yml
- task: Bash@3
    displayName: Install azd
    inputs:
      version: '1.17.0'
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash
        azd version
```

![Image](https://github.com/user-attachments/assets/b0b5a99a-a550-4e61-8dc4-55c502587db9)

**Comment by joseph-hungerman** [comment]
It's not a bash task. It's a specific ***@***.*** task

Joseph Hungerman
Founder/CEO
SEE-EYE, Inc.
ph: (615) 559-9495
em: ***@***.***

https://see-eye.io<https://see-eye.io/>

Let's meet! https://savvycal.com/joseph-hungerman
________________________________

**Comment by faisalriazz** [comment]
@joseph-hungerman , Thank you very much for your kind guidance and direction.

**Comment by faisalriazz** [comment]
Here is the complete step by step procedure to solve this issue. 
- Install `install azd` from https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd.
- replace your old pipeline task 
```yml
- task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash
        azd version
   ```
with this one
```yml
- task: setup-azd@1
    displayName: Install azd
    inputs:
      version: '1.17.0'
```    
Issue is resolved 💯

**Comment by earloc** [comment]
For the folks not able to use the dedicated `install-azd` - task mentioned above:
Specifying the `--version` to the install-script also resolves the issue.

```yaml
- task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version 1.17.0
        azd version
```
