### ISSUE TITLE
docs: OIDC support for other CI providers

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#5417]
With #5397, azd supports OIDC for other CI providers, i.e. GitLab. This issue tracks any doc updates related to the feature.

**Comment by weikanglim** [comment]
Some suggestions I was thinking about:

- Mention this in the release blog post. It could be worthy to put in a small e2e sample (like the one for GitLab below)
- Possible mention in https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/pipeline-advanced-features for:
   - The flag to enable the feature: `--federated-credential-provider oidc`
   - The variables: `AZURE_OIDC_TOKEN` and `AZURE_OIDC_REQUEST_TOKEN`/`AZURE_OIDC_REQUEST_URL`

A minimal GitLab example would look something like:

```yaml
variables:
  AZURE_CLIENT_ID: "<client-id>"
  AZURE_TENANT_ID: "<tenant-id>"

auth:
  id_tokens:
    AZURE_OIDC_TOKEN:
      aud: api://AzureADTokenExchange
  script:
    - azd auth login --client-id $AZURE_CLIENT_ID --tenant-id $AZURE_TENANT_ID --federated-credential-provider oidc
    - azd auth login --check-status
```
