### ISSUE TITLE
Improve default azure.yaml when `azd init` empty template is run

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#783]
Run `azd init` empty template and you get this azure.yaml

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: TheCatSaidNo
infra:
    provider: ""
    path: ""
    module: ""
pipeline:
    provider: ""
```

Let's get 'services' and potentially other useful info in there.
