### ISSUE TITLE
[Issue] `azd show` output does not include the application name

### ISSUE THREAD

**Issue by philliphoff** [Azure/azure-dev#793]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

`azd version 0.3.0-beta.1 (commit c5344160ed49bfda75281fba28b5e9ac7b96670e)`

**Output from `az version`** 

```json
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.2.0",
    "fidalgo": "0.1.0",
    "log-analytics": "0.2.2"
  }
}
```

**Describe the bug**
While the `azure.yaml` contains the name of the application,  the output of `azd show` does not. This means tooling must either parse `azure.yaml` itself or try to infer a name elsewhere.

**To Reproduce**
Run `azd show --output json`

Sample `azure.yaml`:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: todo-nodejs-mongo
metadata:
  template: todo-nodejs-mongo@0.0.1-beta
services:
  web:
    project: ./src/web
    dist: build
    language: js
    host: appservice
  api:
    project: ./src/api
    language: js
    host: appservice
```

Sample output:

```json

{
  "services": {
    "api": {
      "project": {
        "path": "/Users/<redacted>/Source/Scratch/vscode-demo/src/api",
        "language": "node"
      },
      "target": {
        "resourceIds": [
          "/subscriptions/<redacted>/resourceGroups/rg-staging/providers/microsoft.web/sites/<redacted>"
        ]
      }
    },
    "web": {
      "project": {
        "path": "/Users/<redacted>/Source/Scratch/vscode-demo/src/web",
        "language": "node"
      },
      "target": {
        "resourceIds": [
          "/subscriptions/<redacted>/resourceGroups/rg-staging/providers/microsoft.web/sites/<redacted>"
        ]
      }
    }
  }
}
```

**Expected behavior**
I would expect that the output of `azd show` include the same name as in `azure.yaml`.
