### ISSUE TITLE
Support for Logic Apps

### ISSUE THREAD

**Issue by marnixcox** [Azure/azure-dev#812]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 0.3.0-beta.1 (commit c5344160ed49bfda75281fba28b5e9ac7b96670e)`

**Output from `az version`** 
```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "application-insights": "0.1.7",
    "arcdata": "1.4.5",
    "init": "0.1.0",
    "managementpartner": "0.1.3"
  }
}
```
**Describe the bug**
After creating the infra I am trying to deploy Logic App Standard workflow content using the following yaml snippet:

```
services:
  workflows:
    project: src\workflows
    host: function
```

This results in:

` azd deploy
Deploying service workflows...
Error: deploying service: packaging service workflows: dotnet publish on project 'C:\Users\user\source\repos\workspace\logicappstandard\src\workflows' failed: exit code: 1, stdout: MSBuild version 17.3.1+2badb37d1 for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.     
, stderr: : exit status 1`

**To Reproduce**
When using the Logic App Standard Visual Studio Code Extension:
[https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code](url)

the following folder structure is created:

```
MyBundleBasedLogicAppProjectName
| .vscode
| Artifacts
  || Maps 
     ||| MapName1
     ||| ...
  || Schemas
     ||| SchemaName1
     ||| ...
| WorkflowName1
  || workflow.json
  || ...
| WorkflowName2
  || workflow.json
  || ...
| workflow-designtime
| .funcignore
| connections.json
| host.json
| local.settings.json

```

**Expected behavior**
azd cli should zip the folder structure and its contents and deploy it to the Logic App.

**Environment**
Information on your environment:
    * Visual Studio Code 1.71.2
    * Azure Logic Apps (Standard) Extension v1.0.40

**Comment by rajeshkamal5050** [comment]
@ellismg @wbreza do we need to add additional host support for deploying to **_Logic App Standard_**

**Comment by marnixcox** [comment]
@wsilveiranz @puicchan

**Comment by ellismg** [comment]
> @ellismg @wbreza do we need to add additional host support for deploying to Logic App Standard

We very may need to do this yes.  The customer error here is due to azd thinking they have a .NET project and we're trying to do a build of it during deploy.  That is a problem in and of itself but I suspect even if we could build this thing we may need extra work to end up deploying it.

**Comment by marnixcox** [comment]
@ellismg Yes please add it. Don't feel it is a lot different than deploying to a function app. And I am sure @wsilveiranz will be happy to provide some guidance.

**Comment by gbassi-bme** [comment]
Is there an update on this issues, would be great if we can automate the deployment of logic apps standard.

**Comment by marnixcox** [comment]
Solution is to add `language: js`  .So there is no need to add an aditional host.

```
workflows:
    project: ./src/workflows
    host: function
    language: js
```

**Comment by ronaldbosma** [comment]
It would be great if this is suported natively. The workaround mentioned by @marnixcox works but it requires an extra dependency on the npm CLI. 

If you have a Logic App with a custom .NET code project, you'll also need a `prepackage` hook to first build the .NET project so its included in the `/lib/custom` folder. Here's an example:

```
  logicApp:
    project: ./src/logicApp/Workflows
    host: function
    language: js  # Logic Apps aren't natively supported by azd yet. By using js, the logic app will be zipped and deployed.
    hooks:
      # This service is a Logic App with custom .NET code project. We need to build the .NET project first
      # in order for the assemblies to be included in the /lib/custom folder of the Logic App
      prepackage:
        shell: pwsh
        continueOnError: false
        interactive: true
        run: dotnet build ../Functions/Functions.csproj --configuration Release
```
