### ISSUE TITLE
[Proposal] Allow infrastructure and services to be deployed interdependent stages

### ISSUE THREAD

**Issue by rjygraham** [Azure/azure-dev#813]
There may be scenarios in which Azure infrastructure to be deployed as part of the "infrastructure" phase requires the deployment of one of the services defined in the `azure.yaml`; therefore, I propose `azd` allow developers to define multiple stages of infrastructure and service deployment within `azure.yaml`.

A real-world example of this requirement is establishing EventGrid topic subscriptions to an `httpTrigger` or `eventGridTrigger` hosted in Azure Functions. The function needs to exist at the time the EventGrid topic subscription resource is deployed, otherwise the subscription validation fails which results in a deployment failure.

Back of the napkin design for an updated `azure.yaml` supporting such functionality:

```yaml
name: sample
infra:
  main:
    module: ./infra/main
  second:
    module: ./infra/second
    dependsOn:
      - infra/main
      - services/api
services:
  api:
    project: ./src/api
    language: py
    host: function
    dependsOn:
      - infra/main
```

The downside of this approach is that it adds unnecessary bloat to `azure.yaml` for less complex scenarios, so I believe it'd be useful to leave the `infra` section and `dependsOn` property optional for those scenarios.

**Comment by weikanglim** [comment]
Thanks for the suggestion. We'll definitely need some way to support this in `azd` to enable things like event grid subscriptions. 

I could think of an alternative that is not as flexible, but perhaps more concrete to the scenario is to introduce pre-deploy and post-deploy hooks for `services`. 

Something like:

```yaml
services:
  api:
    project: ./src/api
    language: py
    host: function
    preDeploy:
       type: bicep
       module: ./infra/pre-deploy
    postDeploy:
       type: bicep
       module: ./infra/post-deploy
```

I think this would also allow additions like pre-deploy health checks and post-deploy operations.
