### ISSUE TITLE
[Issue] Pack and push NuGet project to Artifacts in Azure Pipelines

### ISSUE THREAD

**Issue by marnixcox** [Azure/azure-dev#901]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 0.3.0-beta.1 (commit c5344160ed49bfda75281fba28b5e9ac7b96670e)`

**Output from `az version`** 
```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "application-insights": "0.1.7",
    "arcdata": "1.4.5",
    "init": "0.1.0",
    "managementpartner": "0.1.3"
  }
}
```
**Describe the bug**
Please advise how to publish a (C#) project as a NuGet package to DevOps Artifacts using azd cli.

[https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops&tabs=nuget](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops&tabs=nuget)

**To Reproduce**
Should the azd cli yaml host enum be extented by something like azdoartifacts? 
```
  "host": {
                        "type": "string",
                        "title": "Type of Azure resource used for service implementation",
                        "description": "If omitted, App Service will be assumed.",
                        "enum": [
                            "",
                            "appservice",
                            "containerapp",
                            "function",
                            "staticwebapp"
                        ]
                    }
```

**Expected behavior**
Project should be build, packaged and pushed by doing the following steps:

```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: Someproject.csproj

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    publishVstsFeed: 'feed id'
  continueOnError: true
```

**Environment**
Information on your environment:
    * Visual Studio Code 1.71.2
