### ISSUE TITLE
[Feature] Offer a Github Action for verifying/linting templates

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-dev#913]
We're developing a number of AZD templates and need a way to statically analyse the templates (without deploying them) so that we can check regressions.

This would involve the following steps:

1. Checking the bicep templates using [`bicep` linter](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/linter)
1. Checking the `azure.yaml` against the YML schema using a schema validator

I'd expect a GitHub Actions template like this:

```yaml

...

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
         uses: actions/checkout@v2
      - name: Verify AZD Template
         uses: azure/verify-azd@latest
```

**Comment by puicchan** [comment]
We should have a command to do this using the CLI without going through GH Action. And we have heard from multiple customers asking for this. @jongio @ellismg

**Comment by jongio** [comment]
@tonybaloney - Def open to a PR if you'd like

**Comment by tonybaloney** [comment]
```yaml
name: Validate bicep scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: az bicep build -f infra/main.bicep
```

This is the simple workflow I've been using. Tried raising a PR with an invalid attribute and an invalid value. It fails for both :+1:

<img width="1549" alt="screenshot 2022-11-18 at 15 50 50" src="https://user-images.githubusercontent.com/1532417/202619512-b1fe3cea-f934-44bf-b701-e21111a029c0.png">
